### ISSUE TITLE
Speed (compared to pyfits and dfits/fitsort)

### ISSUE THREAD

**Issue by thusser** [esheldon/fitsio#102]
Hi,

I often need to read single header keywords from thousands of FITS files.

What I did in the beginning was using pyfits and read every single header and fetch the information that I need. So something like this:

```
from astropy.io import fits
hdr = [fits.getheader(f) for f in files]
```

I just did a test, and with 7000 FITS files this takes about 70 seconds.

So what I'm doing at the moment is a system call to dfits/fitsort, i.e. something like this:

```
dfits = subprocess.Popen(['dfits'] + files, stdout=subprocess.PIPE)
fitsort = subprocess.check_output(['fitsort'] + keywords, stdin=dfits.stdout).decode('utf-8')
dfits.wait()
```

This way, it only takes about 7 seconds to get the data from all files. But, as a downside, I need to now the keywords that I need before running this command (and I also need to parse the output).

Now I' m trying the same with fitsio, hoping for some improvement in speed as compared to pyfits. Getting close to the dfits/fitsort version would be nice. So this is what I do:

```
import fitsio
hdr = [fitsio.read_header(s) for s in args.spectra]
```

Unfortunately this also takes about 50 seconds, so not nearly as fast as I was hoping for.

Is there any other way to get this being done faster? Thanks.

Cheers,
Tim

**Comment by esheldon** [comment]
Currently fitsio loads all the HDU information when it opens a file, which is good for most cases but might cause significant overhead in this case.

What version of fitsio are you using?

I might be able to find a speedup but I'd first like to know what I should be comparing against.

**Comment by thusser** [comment]
For the test I used the latest version in PIP, which is 0.9.10. I could easily change to the current master branch, if that helps. Python version is 3.5.2.

**Comment by esheldon** [comment]
just realized much of the speedup for this dfits program is coming from using a subprocess.

**Comment by thusser** [comment]
Are you sure? I'm just looking at the dfits sources, which you can find by a simple google search, e.g. at:
ftp://134.171.42.54/scisoft/scisoft4/linux/redhat9/eclipse/eclipse/qfits/saft/dfits.c

There it's really just a simple loop over all files:
```
while (c_arg < argc) {
	err += dump_fits(argv[c_arg], xtnum);
	c_arg++;
}
```

dump_fits_filter (called from dump_fits) also just reads in the files sequentially...

**Comment by esheldon** [comment]
sorry, I misinterpreted your code above:  I thought you were spawning a process for each file.

**Comment by thusser** [comment]
Ah, okay. No, I don't. But maybe I could try that in Python with fitsio...

**Comment by odemangeon** [comment]
I found this post, because I have a similar problem. @thusser, did you found a solution ?

**Comment by esheldon** [comment]
I've created a branch #102 with a faster `read_header`, can you please give it a try?

This version is faster but there is still a lot of overhead creating the FITSHDR object itself.  If you know your header keyword is a string, or you know  how to convert it to the required data type yourself, you can use the even faster `read_header_list` function that I've also added.

**Comment by esheldon** [comment]
Note we changed to setuptools recently so your old fitsio will need to be removed before installing with setup.py.  Make sure to remove all fitsio dirs and egg files/directories

**Comment by esheldon** [comment]
I added some more optimizations that made the `read_header_list` version not needed any more (type conversions are now in C).  Please try `read_header` with this version
