### ISSUE TITLE
ImportError: cannot import name _fitsio_wrap

### ISSUE THREAD

**Issue by erwin0825** [esheldon/fitsio#104]
I downloaded the zip file from github and ran `python setup.py install`. I checked that the installation was complete. However,  when I tired to import fitsio, I got the following error. 
```

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "fitsio/__init__.py", line 9, in <module>
    from . import fitslib
  File "fitsio/fitslib.py", line 29, in <module>
    from . import _fitsio_wrap
ImportError: cannot import name _fitsio_wrap
```

**Comment by esheldon** [comment]
It looks like you ran python from the source code directory, the same directory where you ran `python setup.py install`

That will fail because python will see the local `/fitsio` and try to load it, rather than the one you installed.

Try changing directories, or opening a new shell.

**Comment by esheldon** [comment]
@erwin0825  I hope you closed this because your problem was solved!
