### ISSUE TITLE
HDUBase.read_header() does autoconversion

### ISSUE THREAD

**Issue by bwinkel** [esheldon/fitsio#106]
The `read_header()` method of `HDUBase` always applies a conversion of certain strings, e.g., "100-10" is silently converted to 90. I can still access the original values using the `records()` method, but this is quite painful. It would be good, if the `convert` keyword argument was made accessible in `read_header`. Also, personally I would prefer `convert=False` as the default, because it can take quite a bit of time to track down related bugs in a program.

**Comment by esheldon** [comment]
Thanks, I did not anticipate that sort of thing.  I think most people will expect the conversions, so I'm not exactly sure what the best approach to this is.

**Comment by esheldon** [comment]
Also, a question:  is that not in the  header as a string?  If not a string, was that a mistake?

**Comment by bwinkel** [comment]
It is a string. Real-world example (using the `.records() method`):

```
 {'card_string': "PROJID  = '74-16   '           / Project ID",
  'class': 150,
  'comment': 'Project ID',
  'dtype': 'C',
  'name': 'PROJID',
  'value': 58,
  'value_orig': '74-16   '},
```

Note, how `value` is different from `value_orig`.

**Comment by bwinkel** [comment]
It would already help, if `read_header` could be changed to the following:

```
    def read_header(self, convert=True):
        return FITSHDR(self.read_header_list(), convert=convert)
```
This would be 100% backwards-compatible, I think.

**Comment by esheldon** [comment]
I'll need to look into it, but it seems that should be converted to a
string not a number.  In other words, this might just be a bug.

On 12/5/16, Benjamin Winkel <notifications@github.com> wrote:
> It would already help, if `read_header` could be changed to the following:
>
> ```
>     def read_header(self, convert=True):
>         return FITSHDR(self.read_header_list(), convert=convert)
> ```
> This would be 100% backwards-compatible, I think.
>
> --
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub:
> https://github.com/esheldon/fitsio/issues/106#issuecomment-264990424


-- 
Erin Scott Sheldon
Brookhaven National Laboratory erin dot sheldon at gmail dot com

**Comment by bwinkel** [comment]
Ok, thank you so much for a great library and great support!

**Comment by esheldon** [comment]
I think @dstndstn added the use of  `ast.literal_eval(value_orig)` to replace the old use of `eval`.  How would you attack this one?

**Comment by esheldon** [comment]
Might want to check for something like this
```
type( ast.parse(header_value).body[0].value )
```
This will be `_ast.BinOp` for binary operations, otherwise should be a scalar

**Comment by dstndstn** [comment]
This has faded out of my memory.  I don't think I've ever used 'ast' for anything else, so I have no expertise to contribute, sorry!

**Comment by esheldon** [comment]
OK, for some reason I thought it was you, sorry.

Anyway, I pushed a change to master than I think fixes this.  Please have a look @bwinkel

**Comment by bwinkel** [comment]
It does. Thanks a lot for the quick fix!
