### ISSUE TITLE
Issue reading HIERARCH keywords

### ISSUE THREAD

**Issue by astrogreen** [esheldon/fitsio#108]
I'm trying to read HIERARCH keywords from a FITS header. CFITSIO [supports this](https://heasarc.gsfc.nasa.gov/docs/software/fitsio/c/f_user/node28.html), but when I load a file with fitsio I just get "COMMENT" keywords. Is this possible?

```python
>>> from astropy.io import fits
>>> import fitsio

# With pyfits:
>>> f = fits.open("file.fits")
>>> list(f['COVAR'].header.keys())
['XTENSION',
 'BITPIX',
 'NAXIS',
 'NAXIS1',
 'NAXIS2',
 'NAXIS3',
 'NAXIS4',
 'NAXIS5',
 'PCOUNT',
 'GCOUNT',
 'EXTNAME',
 'COVARMOD',
 'COVAR_N',
 'COVARLOC_1',
 'COVARLOC_2',
 'COVARLOC_3',
 'COVARLOC_4',
 'COVARLOC_5']

# With fitsio:
>>> h = fitsio.read_header("file.fits", "COVAR")
>>> h.keys()
['XTENSION',
 'BITPIX',
 'NAXIS',
 'NAXIS1',
 'NAXIS2',
 'NAXIS3',
 'NAXIS4',
 'NAXIS5',
 'PCOUNT',
 'GCOUNT',
 'EXTNAME',
 'COVARMOD',
 'COVAR_N',
 'COMMENT',
 'COMMENT',
 'COMMENT',
 'COMMENT',
 'COMMENT']

>>> fitsio.__version__
0.9.10

>>> sys.version
3.4.3 (v3.4.3:9b73f1c3e601, Feb 23 2015, 02:52:03)
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)]
```

**Comment by esheldon** [comment]
Thanks for the report.  Can you please make an example file available for testing?

**Comment by esheldon** [comment]
I can take a look if you make a file available.

**Comment by astrogreen** [comment]
I've created the attached example fits file with the following script:

```python
# FITSIO Test of HIERARCH Keywords:

from astropy.io import fits
import fitsio

p = fits.PrimaryHDU()

p.header['COVARLOC_1'] = 1
p.header['COVARLOC_2'] = 10
p.header['COVARLOC_3'] = 13

fits.HDUList([p]).writeto('fitsio-test.fits')

h = fitsio.read_header('fitsio-test.fits')

assert 'COVARLOC_3' in h.keys()
```


[fitsio-test.fits.zip](https://github.com/esheldon/fitsio/files/832702/fitsio-test.fits.zip)

**Comment by esheldon** [comment]
This works for me.

Have you tried installing a newer version of fitsio?

**Comment by astrogreen** [comment]
So 0.9.10 is the latest version available via pip (and in the repository). I cloned the repository and built it, and it does work correctly with the tip of the master branch. 

I see there is a commit with a note about fixing a bug with HIERARCH keywords after the last release. Maybe these changes could be packaged into a release?

**Comment by esheldon** [comment]
OK,thanks.  It did sound familiar!

I'll make a new release.
-e

On 3/12/17, astrogreen <notifications@github.com> wrote:
> So 0.9.10 is the latest version available via pip (and in the repository). I
> cloned the repository and built it, and it does work correctly with the tip
> of the master branch.
>
> I see there is a commit with a note about fixing a bug with HIERARCH
> keywords after the last release. Maybe these changes could be packaged into
> a release?
>
> --
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub:
> https://github.com/esheldon/fitsio/issues/108#issuecomment-285983562


-- 
Erin Scott Sheldon
Brookhaven National Laboratory erin dot sheldon at gmail dot com

**Comment by esheldon** [comment]
version `0.9.11` released

**Comment by astrogreen** [comment]
Wonderful. Thanks for the help!
