### ISSUE TITLE
wrong exception thrown for missing header keyword

### ISSUE THREAD

**Issue by imcgreer** [esheldon/fitsio#109]
In  `FITSHDR.__getitem__` (https://github.com/esheldon/fitsio/blob/master/fitsio/fitslib.py#L4038), if the keyword is missing it is meant to throw an exception as:
`raise ValueError("unknown record: %s" % key)`
but the variable `key` is not defined within the function, and so a NameError results instead. This bug was introduced by da8e14a7b40e4001fbccd0aebf254e62314268d6.

**Comment by esheldon** [comment]
Thanks for the bug report.

Now that I look at this, it may be that we should raise `KeyError`

**Comment by imcgreer** [comment]
I would agree with that -- in fact I had translated code that was previously using pyfits, which did throw `KeyError`, to fitsio, and changed all my exception handlers to catch `ValueError`. But then that broke with this bug. Thanks!

**Comment by esheldon** [comment]
OK, I fixed in master.  Please give it a try.

**Comment by imcgreer** [comment]
worksforme, thanks!
