### ISSUE TITLE
Python 3

### ISSUE THREAD

**Issue by cdeil** [esheldon/fitsio#11]
Do you plan to make `fitsio` Python 3 compatible?

Currently I get this error after fixing a few trivial `print` statement fixes:
```
$ python3.2 -c 'import fitsio; fitsio.test.test()'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/deil/Library/Python/3.2/lib/python/site-packages/fitsio/__init__.py", line 244, in <module>
    from . import fitslib
  File "/Users/deil/Library/Python/3.2/lib/python/site-packages/fitsio/fitslib.py", line 35, in <module>
    from . import _fitsio_wrap
ImportError: dlopen(/Users/deil/Library/Python/3.2/lib/python/site-packages/fitsio/_fitsio_wrap.so, 2): Symbol not found: _PyInt_AsLong
  Referenced from: /Users/deil/Library/Python/3.2/lib/python/site-packages/fitsio/_fitsio_wrap.so
  Expected in: flat namespace
 in /Users/deil/Library/Python/3.2/lib/python/site-packages/fitsio/_fitsio_wrap.so
```

**Comment by esheldon** [comment]
I've created a new branch py3.  It passes all my tests on my linux box.  Please give it a try.

I don't think the test suite has complete coverage of all possible issues, in particular regarding strings/bytes.  Also I have not tested on OS X (and windows support is still minimal for both python 2 and 3).

**Comment by esheldon** [comment]
the test suite is fitsio.test.test()

**Comment by mfouesneau** [comment]
Hi Erin,

All tests work fine on my computer. 

My preliminary other tests are also  working fine. 

I found that reading the header does not include TUNIT keywords in the value from :func:`TableHDU.get_info` but I could access through the :func:`TableHDU.read_header` method

I could not find how to keep the comments on keywords in the header definition. I suppose I have to pass a list of dicts, one per keywords?

That's a great job! Thanks!

**Comment by esheldon** [comment]
Is the header behavior different from python2?

Yes, to specify a comment for a keyword you need to use a list of dicts or a FITSHDR object.

**Comment by mfouesneau** [comment]
I think it's the same behavior.

**Comment by esheldon** [comment]
OK, can you open a separate issue for that?  thanks.

**Comment by mfouesneau** [comment]
Done: https://github.com/esheldon/fitsio/issues/31
