### ISSUE TITLE
update_hdu_list slow for large files

### ISSUE THREAD

**Issue by StuartLittlefair** [esheldon/fitsio#111]
when accessing large multi extension FITS files which are being written to in real-time, I am using ```update_hdu_list``` to make sure fitsio ```FITS``` object is up-to-date. This can be very slow; e.g for 50 000 HDUs, an update takes around 3 minutes. 

Perhaps there is a more efficient way of incrementally finding the number of HDUs present in a large MEF file?

**Comment by esheldon** [comment]
I've never done tests where the number of hdus exceeded a hundred or so, so I don't have any intuition about this.

Are the extensions also large?

What file systems  have you tried this on?  I could imagine some being slower, e.g. distributed file systems like gpfs, reading will slow down dramatically if a file is being written to.

**Comment by esheldon** [comment]
I did a test on a local disk and on gpfs

for small 1k hdus, 50,000 hdus total, the `update_hdu_list` call takes about 2.5-3 seconds on both systems

for 1M hdus it takes 3 seconds on local disk, 34 seconds on gpfs

If there are multiple jobs writing into that directory it could get much slower.

**Comment by esheldon** [comment]
Now if I turn on rebuild=False it is very fast, `2 x 10^{-4}` seconds even on gpfs

```python
fits.update_hdu_list(rebuild=False)
```

**Comment by esheldon** [comment]
Here is my full example:
```python
import time
import numpy
import fitsio

fname='test.fits'

ntot=50000
tm0=time.time()
with fitsio.FITS(fname, 'rw', clobber=True) as fits:

    for i in range(ntot):
        print("    %d/%d" % (i+1,ntot),end=' ')
        d = numpy.random.normal(size=(100,100))
        
        tm=time.time()
        fits.write(d)

        if i > 48000:
            fits.update_hdu_list(rebuild=False)
        print(time.time()-tm)

print("total time:",time.time()-tm0)

```

**Comment by esheldon** [comment]
If you are just appending new hdus, you can turn on `rebuild=False` for this speedup.

**Comment by StuartLittlefair** [comment]
Thanks for looking into this, ```rebuild=False``` does indeed make things very fast - I should read docs more carefully!

**Comment by esheldon** [comment]
OK, that's good to hear.

Can you please update the astropy folks about this on the mailing list?
