### ISSUE TITLE
Support HTTP file access method

### ISSUE THREAD

**Issue by irasnyd** [esheldon/fitsio#113]
cfitsio has supported HTTP/FTP URL based access since version 2.0, but the fitsio Python module does not support this due to a check for a local file using `os.path.exists()`.

https://github.com/esheldon/fitsio/blob/master/fitsio/fitslib.py#L350

I have confirmed that if I monkey patch `os.path.exists()` to always return `True`, the fitsio Python module can access files over HTTP.

I understand that providing a nice error message to users is useful, but perhaps adding a way to skip the check would be beneficial.

**Comment by esheldon** [comment]
Thanks for the report.  Do you have a suggested way to check if this filename is a valid url?

Also do you have a good way of testing this in the test suite?

**Comment by esheldon** [comment]
actually, as you suggest we could just pass the filename along and let cfitsio deal with it for the read only case.  For 'rw' and clobber we would still need to look at the file path.

**Comment by esheldon** [comment]
I've done this in the branch passname.  It works for me.  please give it a try.

**Comment by irasnyd** [comment]
Yep, this works perfectly. Thanks!

**Comment by esheldon** [comment]
I don't think I ever merged this, is that correct?

**Comment by irasnyd** [comment]
Yes, the change in the passname branch works perfectly for this case.
