### ISSUE TITLE
write_key argument names

### ISSUE THREAD

**Issue by kadrlica** [esheldon/fitsio#126]
Is there a reason that the first argument to `write_key` is called `keyname` instead of `name`? The README suggests that you can pass the same arguments to `write_key` as used to create a `FITSHDR` or write with the `header=` option. I don't think this will work if your dictionary consists of `name`, `value` and `comment` fields as suggested by these other methods.

**Comment by esheldon** [comment]
Sorry, is the question about whether the docs are correct?

You can get what you want by doing
```python
write_key(name, value, comment=)
```
but you are correct it does not take a dict.  Is that the issue?

**Comment by kadrlica** [comment]
Oh, sorry for being confusing. I think an example would do best. These all work (as documented):
```
hlist = [{'name':'observer', 'value':'ES', 'comment':'who'},
         {'name':'location','value':'CTIO'},
         {'name':'photometric','value':True}]

fits.write(data, header=hlist)
hdr=FITSHDR(hlist)
fits.write(data, header=hdr)
fits[1].write_keys(hlist)
```
However, counterintuitively (to me), this *does not* work:
```
for hdict in hlist:
    fits[1].write_key(**hdict)
```
The problem is that the first argument in `write_key` is `keyname` instead of `name`:
[`def write_key(self, keyname, value, comment="")`](https://github.com/esheldon/fitsio/blob/89e09660048f2c75918710b90b015f260a139e2d/fitsio/fitslib.py#L1280)

My suggested change would be to change this to:
```def write_key(self, name, value, comment="")```

**Comment by esheldon** [comment]
good idea, I'll make the change

**Comment by esheldon** [comment]
This is in master now

**Comment by kadrlica** [comment]
Thanks!
