### ISSUE TITLE
Version not updated for 0.9.12rc1

### ISSUE THREAD

**Issue by kadrlica** [esheldon/fitsio#129]
I thought I was having trouble installing `0.9.12rc1` and then I realized the version hadn't been updated in [`__init__.py`](https://github.com/esheldon/fitsio/blob/v0.9.12rc1/fitsio/__init__.py#L7) and [`setup.py`](https://github.com/esheldon/fitsio/blob/v0.9.12rc1/setup.py#L190).

Not a big deal, but documenting in case others run into the same "issue".

**Comment by esheldon** [comment]
I put this into master but not going to backport into the release candidate

hopefully this practice will help me remember for next time
