### ISSUE TITLE
Remove temporary testing files

### ISSUE THREAD

**Issue by kadrlica** [esheldon/fitsio#132]
There are a few vestigial files (`test.py` and `test_x.fits`) in the top level directory that should be deleted. The commit message for these is "Temporary addition of testing files (to be removed later)".

I can speak from experience that I've been fooled by these files at least twice... (shame on me?).

**Comment by kadrlica** [comment]
This should probably be done in time for v1.0 (#127)

**Comment by esheldon** [comment]
done
