### ISSUE TITLE
Problem reading lossless fpack'd files?

### ISSUE THREAD

**Issue by albireox** [esheldon/fitsio#141]
Not sure if this is a fitsio or cfitsio proble, but I'm getting an error when I try to read a file compressed with fpack using the lossless gzip format (`-g -q 0`). I can ready the extensions that are float, but when I try to access a extension that has type integer I get this traceback

```
In [10]: ff[3]
Out[10]:

  file: manga-8485-12701-LOGCUBE-SPX-GAU-MILESHC.fits.fz
  extension: 3
  type: IMAGE_HDU
  extname: MASK
  image info:
    compression: GZIP_2
    data type: i2
    dims: [4563,74,74]

In [11]: ff[3].read()
---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
<ipython-input-11-90d44da6f923> in <module>()
----> 1 ff[3].read()

~/.pyenv/versions/3.6.3/Python.framework/Versions/3.6/lib/python3.6/site-packages/fitsio/fitslib.py in read(self, **keys)
   3019         dtype, shape = self._get_dtype_and_shape()
   3020         array = numpy.zeros(shape, dtype=dtype)
-> 3021         self._FITS.read_image(self._ext+1, array)
   3022         return array
   3023

OSError: FITSIO status = 412: datatype conversion overflow
Numerical overflow during type conversion while reading FITS data.
error reading compressed byte stream from binary table
```
Astropy seems to be able to handle the file correctly, so that data is not lost.

**Comment by albireox** [comment]
Hacking around I found that if I do `ff[3]._info['img_equiv_type'] = 8` then `ff[3].read()` works as expected, returning an array of `uint8` (which is ok for the data of that extension). `_info['img_equiv_type'] = 10` also works but 16 or higher produces the error above.

**Comment by esheldon** [comment]
Thanks for the report.  Do you mind making that file available for testing?

**Comment by albireox** [comment]
I have uploaded the file [here](https://faculty.washington.edu/gallegoj/fpack_test/manga-8485-1901-LOGCUBE-SPX-GAU-MILESHC.fits.fz)

**Comment by esheldon** [comment]
This is happening at the C level, in cfitsio. It might be a cfitsio bug.

**Comment by esheldon** [comment]
I checked and this is happening in cfitsio itself

**Comment by esheldon** [comment]
I downloaded the most recent cfitsio and I can properly read the file.

So in order to fix this issue I will need to migrate fitsio to use the more recent cfitsio

**Comment by albireox** [comment]
Great! Thanks for looking into this.

**Comment by esheldon** [comment]
Note we are working to get the latest cfitsio working.  We should have an update soon.

**Comment by esheldon** [comment]
please try again with the master branch, I think this may be fixed

**Comment by albireox** [comment]
Confirmed! It works with the file I had problems originally.

**Comment by esheldon** [comment]
great, thanks for the report
