### ISSUE TITLE
import numpy in setup.py

### ISSUE THREAD

**Issue by dkirkby** [esheldon/fitsio#143]
The unconditional `import numpy` in setup.py is causing my [readthedocs builds to fail](https://readthedocs.org/projects/bossdata/builds/6426290/).  I can probably work around this, but do you really want to require that numpy is installed just to run `python setup.py egg_info` on your pkg?  Perhaps you could wrap your `import numpy` in a try or a function that is only called when actually needed?

**Comment by esheldon** [comment]
Please try the current master

**Comment by dkirkby** [comment]
It works now, thanks.  For proof, here's a [sample RTD log](https://readthedocs.org/projects/bossdata/builds/6431442/) that now successfully pip installs `fitsio` (from the github master branch) but failed before.  I will need to update my `docs/rtd-pip-requirements` to point back to pypi once your change propagates there.
