### ISSUE TITLE
reading combination of columns from an extension

### ISSUE THREAD

**Issue by fvisconti** [esheldon/fitsio#148]
Is there already the chance to read not just a column from a Binary Table, but a combination of columns?

for example:
```
hdu = FITS('file')
events = hdu['EVENTS']
expression = 'log10(col1) * col2'
events[expression].read()
```

The reason why I want to do this is that I only know `expression` at run time (via a configuration file).

It seems the `CFITSIO` can do this via the `readKey()` function.

**Comment by esheldon** [comment]
I'm not aware of `readKey()`, can you please point me to the documentation?

**Comment by esheldon** [comment]
That is the C++ code `CCFits` not `CFITSIO`

Also that simply reads a keyword from the header, it does not perform mathematical operations

**Comment by fvisconti** [comment]
You are right, I was trying to understand a little better indeed.
As soon as I understand I'll tell you something more.

**Comment by fvisconti** [comment]
I can do like this:
first I read all columns needed into properly named arrays, like:
```
col1 = events['col1'].read()
col2 = events['col2'].read()
```
I can then import from `numpy` import the functions allowed to be used (I cannot but impose this but it's fine) such as `log10` or trigonometric, and then use `eval` like this:
```
from numpy import log10
par1 = 'log10(col1)'
par1_col1 = eval(par1)
```

It works pretty fine, thanks to [@elehcim](https://github.com/elehcim)

**Comment by esheldon** [comment]
That will work, but will be inefficient.  This way is faster, because one must only go through the file one time to read the data

```python
with FITS(filename) as hdu:
    events = hdu['EVENTS']
    data = hdu.read(columns=['col1','col2'])
    col1 = data['col1']
    col2 = data['col2']
    expression = 'log10(col1) * col2'
    par1_col1 = eval(expression)
```

**Comment by fvisconti** [comment]
Of course you're right.

Since there are details I didn't tell, I paste here the final version:

```python
def set_data_for_training(path, filters, npar, *args, **kwargs):
    """Generates event list with npar number of features defined in
    *args. To see what args can be, refer to PARFILE_NAME
    """
    # this imports allowed math functions
    from numpy import log10, cos, sin

    for f in scand(path):
        if f.name.endswith('.lv1b'):
            with fitsio.FITS(path + f.name) as hdu:

                mask = hdu["EVENTS"].where(filters)

                # the events variable defined here is used in eval function
                events = hdu["EVENTS"][mask]

                evts_feat = np.zeros(shape=(len(events), npar))

                for i in range(npar):
                    evts_feat[:, i] = eval(args[i])

                yield evts_feat
```

**Comment by esheldon** [comment]
Is this working now for you?  Can we close the issue?

**Comment by fvisconti** [comment]
Yes
