### ISSUE TITLE
remove rows from existing Bin Table

### ISSUE THREAD

**Issue by fvisconti** [esheldon/fitsio#151]
This issue may be similar to #79, but I'm not sure.
I just need to remove rows from an existing BinTable, but I can only find the `append` method or overwriting methods: I suspect there's a reason not to have a sort of `delete` method, but can somebody make it clear to me?

**Comment by esheldon** [comment]
there is code in cfitsio to do this, but it is not yet "exposed" in the python level

**Comment by esheldon** [comment]
I've got a version of this working in the branch feature-row-modifications

**Comment by esheldon** [comment]
I'm going to close this because it now works in master

**Comment by fvisconti** [comment]
Great!
