### ISSUE TITLE
Trouble reading GZIP_2 mask plane

### ISSUE THREAD

**Issue by kadrlica** [esheldon/fitsio#153]
Attn: @erykoff 
Poking around simulated, processed LSST calexp images and found that there was trouble reading the mask plane. The mask is `GZIP_2` compressed and when I read it the resulting array is uniquely zeros. In contrast, if I `funpack` the file and then read the HDU it comes out as a non-zero `int32` array.

An example file can be found on NERSC here:
```
/global/cscratch1/sd/jchiang8/DC2/phosim_Run1.1p/phosim_bg_studies/output_33/calexp/v417009-fr/R22/S00.fits
```

To `funpack` I did:
```
cp /global/cscratch1/sd/jchiang8/DC2/phosim_Run1.1p/phosim_bg_studies/output_33/calexp/v417009-fr/R22/S00.fits ~/S00.fits.fz
funpack ~/S00.fits.fz
```

**Comment by esheldon** [comment]
I think this is addressed in master
