### ISSUE TITLE
Problems when header contains string 'None'

### ISSUE THREAD

**Issue by menanteau** [esheldon/fitsio#163]
The latest version of fitsio has a issue when they value of a keyword contains the string 'None'. An example of problematic image with such header can be downloaded from: http://cosmology.illinois.edu/~felipe/fistio-issue/D00604341_i_c10_r2988p01_immasked.fits.fz

`f = fitsio.FITS('D00604341_i_c10_r2988p01_immasked.fits.fz')`
`header = f['SCI'].read_header()`
`for k in header:
    print(header[k])`
```---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-9-f1da4b2dc8ec> in <module>()
      1 for k in header:
----> 2     print(header[k])
      3 

/Users/felipe/EUPS_DESDM/eups/packages/DarwinX86/fitsio/1.0.0rc1+0/python/fitsio/fitslib.pyc in __getitem__(self, item)
   4242         val = self.get(item,None)
   4243         if val is None:
-> 4244             raise KeyError("unknown record: %s" % item)
   4245         return val
   4246 

KeyError: 'unknown record: ERRORS'```

**Comment by esheldon** [comment]
I think this is now fixed.  Do you agree?
