### ISSUE TITLE
Issues installing at NERSC

### ISSUE THREAD

**Issue by damonge** [esheldon/fitsio#166]
After an uneventful `pip install fitsio --user`, when importing fitsio from anaconda's python-3.6 at Cori, I get:
```
ImportError: /global/homes/d/damonge/.local/cori/3.6-anaconda-4.4/lib/python3.6/site-packages/fitsio/_fitsio_wrap.cpython-36m-x86_64-linux-gnu.so: undefined symbol: __intel_sse4_strncat
```

Any idea what's happening?

**Comment by esheldon** [comment]
I have not attempted to install fitsio this way at nersc.  I have only been working with docker images, and shifter.  Maybe someone else can comment.

**Comment by damonge** [comment]
Thanks. I managed to fix it by loading the GNU compilers instead of the intel ones, so it's not really an issue anymore (except that conflicts with some of my other modules which I've had to reinstall, but anyway).
