### ISSUE TITLE
read_header convert issue

### ISSUE THREAD

**Issue by jzoubian** [esheldon/fitsio#167]
Hi,

I ran into an issue when reading some particular header value like:
```
TEST   = '52926_1 '           / test case
```

With fitsio (version >=  0.9.9.1), I have the following result:
```python
>>> import fitsio
>>> head = fitsio.read_header('test.fits')
>>> print(head['TEST'])
529262 
>>> print(type(head['TEST']))
<class 'int'>
```

In HDUBase.read_header, FITSHDR is initialized with `convert=True`. If I disable  the conversion, I have the expected resulting string ie `52926_2`.

I also have the correct behavior with fitsio version 0.9.8.

Thank you in advance for your help!

**Comment by esheldon** [comment]
This works for me in recent master.  Can you try the tag 1.0.0rc1 please?

**Comment by jzoubian** [comment]
Thanks a lot for the fast answer!

I have this issue also with the master:
```python
>>> import fitsio
>>> print(fitsio.__version__)
1.0.0rc1
>>> head = fitsio.read_header('test.fits')
>>> print(head['TEST'])
529261
>>> print(type(head['TEST']))
<class 'int'>
```

I created the test case with fitsio:
```python
>>> import fitsio
>>> hlist = [{'name':'TEST', 'value':'52926_1', 'comment':'test case'}]
>>> fitsio.write('test.fits', data=None, header=hlist)
```

I forgot to mention, I'm using python 3.6.5, numpy 1.14.5 and gcc 7.3.0

**Comment by esheldon** [comment]
OK, can you please try with master?  Maybe it was a recent fix.

**Comment by jzoubian** [comment]
I still have the same results...

**Comment by esheldon** [comment]
OK, sorry.  The repr for the header showed the correct value but when I actually extract the value it is indeed an int.  I'll look into it more.

**Comment by esheldon** [comment]
This is a python3 issue.

In a recent release, this became a valid integer literal:  `1_000_000` which means 1 million.  That wasn't true in older releases.

A fix might be the following logic.
```python
res=eval(header_string)
if type(res)==int and '_' in header_string:
    res=header_string
```

**Comment by jzoubian** [comment]
Hi,

I tried a quick and dirty patch to test your proposition and this work for me.
```

**Comment by buchbend** [comment]
Dear all, I ran into the same issue with the latest master. We have project numbers that look e.g. "06_0017_1" in our fits headers and these are converted to an integer, when the first digit is not 0. Is this fix going to be implemented?

**Comment by esheldon** [comment]
I put a fix into branch #167, and I've got a pull request in #190

**Comment by esheldon** [comment]
The PR has passed travis tests and is ready to merge.  Can you please give it a try on branch #167 ?

**Comment by buchbend** [comment]
I gave branch #167 a try and can confirm that it reads strings like "83_0509_9" correctly (I only tested 
`fitsio.read_header`). I cross checked with the current master which reads the same header value as "8305099". The fix is working as far as I can see.
