### ISSUE TITLE
Checking writting of a fits file

### ISSUE THREAD

**Issue by TEtourneau** [esheldon/fitsio#169]
Hello,

is there a way to check that the writting of a fits file with fitsio occurs normaly and doesn't experience any problem or error ? 
For example if at some point, there is a hardware problem that prevents the writting of a file. Can I know that ?

Thank you in advance,

Thomas

**Comment by esheldon** [comment]
Usually an exception will be raised, such as `OSError` or `IOError`.

If an exception is not raised, but there is an error in writing or if there is disk corruption later, you can check this by using the checksums. 

```python

# add checksums for the data in an extension
with fitsio.FITS(fname,'rw') as fits:
    fits.write(some_data, ext=ext)
    fits[ext].write_checksum()

# can later verify data integrity
fits[ext].verify_checksum()
```

**Comment by beckermr** [comment]
This question appears to have been answered. I am closing this issue. Feel free to reopen if you have more questions!
