### ISSUE TITLE
Conda package for fitsio is broken

### ISSUE THREAD

**Issue by weaverba137** [esheldon/fitsio#170]
The [openastronomy conda channel](https://github.com/OpenAstronomy/conda-channel) provides a conda package for fitsio, but it is currently broken.

1. When installing in a Python 3 distribution, conda somehow prefers the Python 2.7 version, even though Python 3 versions are available.
2.  The latest version, 0.9.11, is not available.
3. The openastronomy channel is no longer actively maintained.

As a workaround, fitsio can be installed with pip.  [conda-forge](https://github.com/conda-forge) is probably the best place for future packages.

**Comment by esheldon** [comment]
Thanks for the issue. I wasn't involved with that conda package.  But I do agree that conda-forge would make sense, and I think it would be a great resource (I would use it).

Does anyone have expertise with conda to make such a package?

**Comment by weaverba137** [comment]
https://conda-forge.org/docs/

**Comment by rainwoodman** [comment]
I would suggest trying to directly submit the package to anaconda, rather than going through conda-forge.

**Comment by beckermr** [comment]
Why @rainwoodman do you suggest submitting to anaconda?

**Comment by rainwoodman** [comment]
- astropy's fits reader is already in anaconda: https://anaconda.org/anaconda/astropy

- a general argument against using conda-forge at all: conda-forge packages overwrite the default anaconda packages, but there is no binary compatibility guarantee between the anaconda packages that comes from "download Anaconda now" and those you get from conda-forge. Think of the early days of wild RPM packages. This will eventually be fixed, but not yet.

Unlike conda-forge, I don't know of a guideline for acceptance into anaconda's default channel -- we can still try to make the case by submitting a recipe. This seems to be a list of accepted new recipes:

https://github.com/AnacondaRecipes/aggregate/pulls?q=is%3Apr+add+recipe+is%3Aclosed

(most are deep learning related : / )

**Comment by beckermr** [comment]
I am not terribly worried about the binary stuff here. You need to list conda-forge first in the channels. They are migrating to new compilers right now and that should help rare cases.

**Comment by beckermr** [comment]
The other thing that is fun here, is that it appears that anaconda inc (the company) forked a large number of the conda-forge recipes for shipping their own defaults. I have been told by a dev for both that the authoritative versions are on conda-forge.

**Comment by rainwoodman** [comment]
Yes I tend to be overly concerned about these inconsistencies; with the dusts settling it will be less of a concern with time.

My own feeling was that the forks might have helped conda-forge to the new compilation tools. Once they have served the purpose the authorize versions are still on conda-forge? ; )
