### ISSUE TITLE
wget in travis tests are failing

### ISSUE THREAD

**Issue by esheldon** [esheldon/fitsio#175]
E.g. this sort of thing is often failing in the travis tests
```
wget ftp://heasarc.gsfc.nasa.gov/software/fitsio/c/cfitsio3430.tar.gz
```

It works from my machine so I'm not sure what's going on

**Comment by esheldon** [comment]
@rainwoodman do you have any suggestions about this wget issue in travis?

**Comment by rainwoodman** [comment]
https://github.com/esheldon/fitsio/pull/171/commits/311c649bce3cdeb160ee8244204bff5ac0b3ce4b

**Comment by esheldon** [comment]
I see, that will be fixed when we merge your other PR
