### ISSUE TITLE
Indexing a scalar item from a TABLE_HDU's column returns a vector.

### ISSUE THREAD

**Issue by rainwoodman** [esheldon/fitsio#177]
Assuming f[1] is a TABLE_HDU with a single DEC column.
```
with .... as f:
    assert f[1]['DEC'][:].ndim = 1
    assert f[1]['DEC'][0].ndim = 0 # fails, the value is one
```

This is version 0.9.11. Has this been brought up before?

The usual indexing convention is to return a scalar in this case, for example if you are indexing from h5py or a numpy array.

**Comment by esheldon** [comment]
@rainwoodman do you have a fix for that?  Originally this code was not meant for that sort of introspection, but we would welcome it I think

**Comment by esheldon** [comment]
actually I misunderstood this, sorry.  The point is that the code is always reading into a vector.

this would be a big change and might break codes.  But do submit a PR and we can consider it.

**Comment by rainwoodman** [comment]
I say there are more benefits to be consistent with the numpy protocol than to be compatible with the old behaviour.  We can add a deprecation warning when one indexes by a scalar index. Then in next version change the behaviour.

**Comment by beckermr** [comment]
I think numpy conventions should be respected. We just tagged 1.0 so we might have missed our chance to change this. OTOH we did not push to pypi so we could try and squeeze it in.
