### ISSUE TITLE
support unicode strings

### ISSUE THREAD

**Issue by beckermr** [esheldon/fitsio#179]
I am making this issue to start a convo around unicode string support for python 3. TBH, this looks like a nightmare. 

Some notes:
- I checked the `cfitsio` docs and it does not appear that they have support for unicode. 
- Right now `fitsio` doesn't itself support the 'U' numpy type (which denotes unicode strings). 

So to make this happen, I think we have to put in manual conversions. On writing, this is straight forward since we would know it is a unicode type before hand and so could convert to a string of bytes (assuming we stick to a fixed length codec, which might cause overhead if we have to convert). 

Reading is the real nightmare though. Basically, if we see a column of bytes, IDK how we would know it was written from a column of unicode strings in python. I was thinking we could reserve `TSTRING` in the fits standard for `NPY_UNICODE` objects, but then if someone wants to write an array of python bytes data from `NPY_STRING`, we would have to use the `TBYTE` fits type. However, this would be confused with an array of unsigned one-byte integers, `NPY_UINT8`. 

Thus we have a many to one issue in that the FITS types are not expressive enough. 

This leaves us with truly awful solutions around monkey patching the header info to hold the extra information on which columns need unicode conversion on read. :donotwant:

So, unless, I am mistaken, we would have to basically write unicode into the FITS standard before we can support it in python 3. 

Thoughts @rainwoodman @esheldon @erykoff ?

**Comment by beckermr** [comment]
Some discussion happened here: https://github.com/esheldon/fitsio/issues/99

conclusion seems the same...

**Comment by esheldon** [comment]
I think the best short-term solution might be to have a constructor keyword that tells fitsio to convert strings to utf-8 numpy strings.

```python
with FITS(fname, read_utf8=True) as fits:
    data=fits[ext].read()
```

**Comment by beckermr** [comment]
Yep. Rereading #99 this seems like the suggestion there. The `native_string` option is actually not crazy either. 

My only complaint is that I would not be able to write a table of both byte strings and unicode strings in python 3.

**Comment by esheldon** [comment]
For more fine grained control of types, we could in principle add a feature like this too:
```python
data=... # make a structure with the types you want
# read in the fields that match the names in the specified
# structure, converting types as necessary
fitsio.read_into(fname, data)
```
Or even specify types on the call
```python
data=fitsio.read(fname, types={some dict mapping names to types})
```

**Comment by beckermr** [comment]
Ahhh yes good point. This is what pandas does. 

Here is a proposal:

1. Default to reading `TSTRING` as UTF-8 in python 3. This might break backwards compatibility for some files, but we can put this into version v1.X. This default is the most common use case (I think?) and preserves functionality between python 2 and python 3 more globally. 

2. Add the type-dict syntax you suggested above to the appropriate spots to let ppl hack around 1 above if they really need to. 

Does that seem workable?

**Comment by beckermr** [comment]
We might want utf-32 actually so the columns are fixed width, but details.

**Comment by beckermr** [comment]
we could also just force ascii everywhere...

**Comment by beckermr** [comment]
Forcing only ascii is a lot simpler FWIW.

**Comment by beckermr** [comment]
Right @erykoff. So we can minimally just implement 1 above and call it good. This will have the weird side effect that 'S' typed ndarrays will come back as 'U' but I think this is ok for python3.

**Comment by beckermr** [comment]
We will need to exclude non-ascii on write because of storage. Basically, the issue here is the kind of encoding we use. UTF-8 is a variable-width encoding, meaning each item in a unicode python string encoded with UTF-8 can take anywhere between 1 and 4 bytes. This variable width is possible to implement but it is easier to just stick to ascii which always encodes as 1 byte. UTF-32 is another option. It would encode each ascii character with 4 bytes. However this wastes space, which is why people use things like UTF-8.

**Comment by erykoff** [comment]
FYI, I just checked and `astropy.io.fits` will raise if you try to write non-ascii unicode to fits (it enforces using the ascii codec).  So I think this is fine (at least it's compatible, which is good).
As for the round-trip `S` in and `U` out, I think that's okay, but our tests will have to be careful.

**Comment by esheldon** [comment]
Sounds like we should start by making sure the input can be coerced into ascii. For py3 we could return ascii encoded stuff rather than bytes.  This will indeed break peoples code I expect but maybe it is for the best.
