### ISSUE TITLE
error with getting some fits records

### ISSUE THREAD

**Issue by beckermr** [esheldon/fitsio#197]
It appears that a fits record with a value 'None' is not processed correctly.

![screen shot 2019-01-11 at 1 16 16 pm](https://user-images.githubusercontent.com/5296416/51054696-3dab4d80-15a3-11e9-90ab-a3cf1f7aa8ae.png)

**Comment by esheldon** [comment]
I think this was addressed in a recent PR #174

**Comment by beckermr** [comment]
But the None value for the keyword then triggers the code to error saying the key is not present. I think the test on line 4041 in fitslib.py is now wrong. The code should be something like

```python
if key not in self._record_map:
    do something
else:
    do something else
```

**Comment by esheldon** [comment]
are you looking in master?  It looks right there

**Comment by beckermr** [comment]
Ack. You are right. 

Can we put out a bug fix release? I know we are punting again on v1 due to the unicode stuff, but it has been 101 commits since the last release.
