### ISSUE TITLE
move from travis to something else

### ISSUE THREAD

**Issue by esheldon** [esheldon/fitsio#201]
nuff said

**Comment by beckermr** [comment]
OS X costs money with circle. We might consider azure

**Comment by esheldon** [comment]
quite a few alternatives are discussed here:  https://news.ycombinator.com/item?id=18978251

**Comment by beckermr** [comment]
Yup. I am genuinely impressed by azure. It is really fast and the logs are easy to look at. The web interface is a bit odd but shrug.

**Comment by esheldon** [comment]
10 parallel jobs seems like plenty for our purposes

**Comment by beckermr** [comment]
Indeed!

**Comment by esheldon** [comment]
If it aint broke, don't fix it
