### ISSUE TITLE
Array size checking fails on (n,1)-shaped arrays (py3)

### ISSUE THREAD

**Issue by dstndstn** [esheldon/fitsio#206]
Hi Erin,

Looks like you've made an impressive amount of progress toward 1.0 -- congrats!

This turned up last night (my CI build suddenly started failing!).

It looks like arrays of size:
 (N,) works
 (N,N) works
 (1,N) works
 (N,1) fails

This last case occurs in the wild (in my code, eg) because we have a "fluxes" column that includes measured fluxes for all available bands, and sometimes there is only one band available.

Test case:
```
import fitsio
import numpy as np
print('numpy', np.__version__)
fitsio.write('x.fits', names=['a'], data=[np.zeros((2,1))])
```

Result (with some commented-out print statements in that vicinity enabled):
```
> python testcase.py
numpy 1.14.5
col_tdim [1]
column name: a
(2, 1)
column dtype: f8
input dtype: f8
column shape: None
input shape: (1,)

Traceback (most recent call last):
  File "testcase.py", line 4, in <module>
    fitsio.write('x.fits', names=['a'], data=[np.zeros((2,1))])
  File "/usr/local/lib/python3.7/site-packages/fitsio/fitslib.py", line 263, in write
    **keys)
  File "/usr/local/lib/python3.7/site-packages/fitsio/fitslib.py", line 509, in write
    write_bitcols=write_bitcols)
  File "/usr/local/lib/python3.7/site-packages/fitsio/fitslib.py", line 818, in write_table
    self[-1].write(data,names=names)
  File "/usr/local/lib/python3.7/site-packages/fitsio/fitslib.py", line 1693, in write
    self._verify_column_data(tcolnum,tdata)
  File "/usr/local/lib/python3.7/site-packages/fitsio/fitslib.py", line 1815, in _verify_column_data
    "expected '%s', got '%s'" % (col_name,col_shape, this_shape))
ValueError: bad input shape for column 'a': expected 'None', got '(1,)'
```
```
> python --version
Python 3.7.2
```

OHH, and interestingly, it seems to work in python2:
```
> python2 testcase.py
('numpy', '1.14.0')

> python2 --version
Python 2.7.15
```

**Comment by beckermr** [comment]
Thanks for the bug report! 

FWIW, It is probably good to not depend on master for CI builds. 

We’ll look into this.

**Comment by beckermr** [comment]
Issue is in this PR by @esheldon: https://github.com/esheldon/fitsio/commit/54aa8df8e051ab1f131a1b26f19e5d57b57b78ae

**Comment by esheldon** [comment]
This never worked for me, not even in python 2, so I'm surprised it works in 2.7

**Comment by esheldon** [comment]
It must have to do with sending `names=` and `data=` which is not a well tested code path.  I have never actually done that in the real world.

**Comment by esheldon** [comment]
I think I misunderstood this issue before.  It isn't that the colum

**Comment by beckermr** [comment]
Ahhh yeah. This is simply an error checking thing.
