### ISSUE TITLE
Header parsing wrongly tries to cast strings to floats

### ISSUE THREAD

**Issue by dstndstn** [esheldon/fitsio#207]
We encountered this one in the wild.  fitsio tries to convert a string like '89113e6' into a float!

Minimal test case:

```
import fitsio
hdr = fitsio.FITSHDR()
val = '89113e6'
hdr['PLPROCID'] = val
fitsio.write('/tmp/1.fits', None, header=hdr)
hdr2 = fitsio.read_header('/tmp/1.fits')
val2 = hdr2['PLPROCID']
print(val2)
assert(val2.strip() == val.strip())
```

Prints `89113000000.0`

It seems like the parsing rule ought to be that if a value is in quotes, it's a string.

**Comment by esheldon** [comment]
Hi @dstndstn please check out the fix in PR #208
