### ISSUE TITLE
tag and release v1.0.0

### ISSUE THREAD

**Issue by esheldon** [esheldon/fitsio#219]
I'm opening an issue so people can comment if we are ready. In particular @beckermr @kadrlica @dstndstn @rainwoodman 

[![](https://api.gh-polls.com/poll/01D88WJKZJSKK6692WJS6AAY4S/shipit)](https://api.gh-polls.com/poll/01D88WJKZJSKK6692WJS6AAY4S/shipit/vote)
[![](https://api.gh-polls.com/poll/01D88WJKZJSKK6692WJS6AAY4S/wait)](https://api.gh-polls.com/poll/01D88WJKZJSKK6692WJS6AAY4S/wait/vote)

**Comment by esheldon** [comment]
poll added

**Comment by beckermr** [comment]
Just ship it. We can release bug fixes later.

**Comment by esheldon** [comment]
I'll take @kadrlica thumbs up as equivalent of a vote on the poll

**Comment by kadrlica** [comment]
I also voted to ship.
