### ISSUE TITLE
Build cfitsio outside of setup.py running

### ISSUE THREAD

**Issue by mindriot101** [esheldon/fitsio#23]
When running the setup.py file e.g. to extract metadata or just download the package with `pip --download <DIR> fitsio` the setup script compiles the packaged version of cfitsio. It would be better to only build this during the install phase.

**Comment by esheldon** [comment]
There is a pull request in now #63 that might make this easier

**Comment by esheldon** [comment]
where do we stand on this?

**Comment by mindriot101** [comment]
This has been fixed - running `python setup.py --version` to get the `fitsio` version string no longer compiles cfitsio.

**Comment by esheldon** [comment]
ok good, will close
