### ISSUE TITLE
where condition

### ISSUE THREAD

**Issue by prajwel** [esheldon/fitsio#230]
Hi, 

   Thanks for the software! I have a question regarding the where condition. 

For me, the following works.
`fits[1].where('time > 279318186.9587704')`

the following does not. 
```
stop_time = 279318186.9587704
fits[1].where('time > stop_time')
```

I get the following error

>Traceback (most recent call last):
>File "<stdin>", line 1, in <module>
>File "/home/prajwel/.local/lib/python3.4/site-packages/fitsio/fitslib.py", line 1637, in where
>   return self._FITS.where(self._ext+1, expression)
>OSError: FITSIO status = 431: syntax error in expression
>ffgcnn could not find column: stop_time
>ffgkey could not find keyword: stop_time
>syntax error`

Could you please help me? Many thanks for any help!

**Comment by esheldon** [comment]
The value isn't provided in the string sent to `where`.  did you mean to make a formatted string, something like this?
```python
stop_time = 279318186.9587704
fits[1].where('time > %g' % stop_time)
```

**Comment by prajwel** [comment]
It worked! Thank you a lot.
