### ISSUE TITLE
Error while appending

### ISSUE THREAD

**Issue by prajwel** [esheldon/fitsio#239]
Hi,

   While trying to append two fits tables, I get the following error. 

```
>>> fits1[1]

  file: AS1A05_056T01_9000002498uvt_level1.att
  extension: 1
  type: BINARY_TBL
  extname: ATTITUDE
  rows: 10129
  column info:
    TIME                f8  
    Q_SAT               f8  array[4]
    Roll_RA             f8  
    Roll_DEC            f8  
    Roll_ROT            f8  
    ATD_STATUS          i1  array[8]
>>> fits2[1]

  file: 1_AS1A05_056T01_9000002498uvt_level1.att
  extension: 1
  type: BINARY_TBL
  extname: ATTITUDE
  rows: 147076
  column info:
    TIME                f8  
    Q_SAT               f8  array[4]
    Roll_RA             f8  
    Roll_DEC            f8  
    Roll_ROT            f8  
    ATD_STATUS          i1  array[8]

>>> fits1[1].append(fits2[1])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/prajwel/.local/lib/python3.4/site-packages/fitsio/fitslib.py", line 1966, in append
    self.write(data, **keys)
  File "/home/prajwel/.local/lib/python3.4/site-packages/fitsio/fitslib.py", line 1688, in write
    if data.dtype.fields is None:
AttributeError: 'TableHDU' object has no attribute 'dtype'
```

Few sample rows of the FITS table are as follows. 

>    2.793168904952E+08      -3.664317696774E-01 -4.951139369490E-01 -1.046185818597E-01 7.807976049781E-01      5.343889371984E+01  -2.794487564369E+01  -7.415632798420E+01    1 1 1 0 0 0 0 0
>    2.793168906232E+08      -3.664332363683E-01 -4.951185083692E-01 -1.046174912968E-01 7.807941639572E-01      5.343870432884E+01  -2.794486863726E+01  -7.415708436014E+01    1 1 1 0 0 0 0 0
>    2.793168907512E+08      -3.664336221366E-01 -4.951200040248E-01 -1.046170343210E-01 7.807930957125E-01      5.343866168795E+01  -2.794486598468E+01  -7.415732258406E+01    1 1 1 0 0 0 0 0

Thanks for any help!

**Comment by beckermr** [comment]
Hi! Thanks for using fitsio! I think the issue here is that we need to be appending the data, not the HDU object. Try the append call with `.read()` like this

```
fits1[1].append(fits2[1].read())
```

**Comment by prajwel** [comment]
Hi @beckermr, thank you for the help! I tried that and it resulted in a new error. 

```
  File "/home/prajwel/.local/lib/python3.4/site-packages/fitsio/fitslib.py", line 1741, in write
    firstrow=firstrow+1, write_bitcols=self.write_bitcols)
OSError: FITSIO status = 310: not a logical (L) column
```
Also, I was using `fits1[1].append(fits2[1])` line without any errors/warnings for some other FITS tables of different format. Would that have corrupted the tables in some way?

**Comment by beckermr** [comment]
Hmmmmm. IDK. Maybe @esheldon can weigh in here?

**Comment by esheldon** [comment]
Maybe.

It might be good to start from scratch with new data.

**Comment by prajwel** [comment]
Hi, sample files are accessible at 

https://www.dropbox.com/s/dl3uf2vxonxjnqf/fits1.att?dl=0
https://www.dropbox.com/s/mb16qo9b08o4nq3/fits2.att?dl=0

The following script reproduces the problem 
```
from fitsio import FITS,FITSHDR
fits1 = FITS('fits1.att', 'rw')
fits2 = FITS('fits2.att')
fits1[1].append(fits2[1].read())
```

**Comment by esheldon** [comment]
The `atd_status` column is written as a bit column.  Currently these are only written when you open the file with `write_bitcols=True`, e.g.
```
with fitsio.FITS('fits1.att','rw',write_bitcols=True) as fits:
    data = fitsio.read('fits2.att')
    fits[1].append(data)
```

The above code works, but it might be that when appending we should check to see if there is a bit col and use that method without the user setting that.

**Comment by esheldon** [comment]
I've got a PR in to fix this, so the it will just work without specifying `write_bitcols=True`

**Comment by esheldon** [comment]
The fix is now in the master branch, and will appear in the next release.

thanks for the report

**Comment by prajwel** [comment]
Thank you for the help! :smile:

**Comment by esheldon** [comment]
you're welcome!
