### ISSUE TITLE
problem reading 2GB gzipped -> 4.3GB unzipped fits file

### ISSUE THREAD

**Issue by sbailey** [esheldon/fitsio#245]
Are there any known issues with reading very large gzipped fits files with fitsio?  We have a case that is 2G gzipped and 4.3G when unzipped.  Reading the unzipped file works fine, but reading the gzipped file gives:
```
In [2]: x = fitsio.read("/global/project/projectdirs/cosmo/work/legacysurvey/dr8
   ...: c/ccds-annotated-decam-dr8.fits.gz")
---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
<ipython-input-2-601d664f415a> in <module>()
----> 1 x = fitsio.read("/global/project/projectdirs/cosmo/work/legacysurvey/dr8c/ccds-annotated-decam-dr8.fits.gz")

/global/common/software/desi/cori/desiconda/20180709-1.2.6-spec/conda/lib/python3.6/site-packages/fitsio/fitslib.py in read(filename, ext, extver, **keys)
     85     """
     86 
---> 87     with FITS(filename, **keys) as fits:
     88 
     89         header=keys.pop('header',False)

/global/common/software/desi/cori/desiconda/20180709-1.2.6-spec/conda/lib/python3.6/site-packages/fitsio/fitslib.py in __init__(self, filename, mode, **keys)
    351                 raise IOError("File not found: '%s'" % filename)
    352 
--> 353         self._FITS =  _fitsio_wrap.FITS(filename, self.intmode, create)
    354 
    355     def close(self):

OSError: FITSIO status = 414: error uncompressing image
failed to uncompress file into memory (compress_open)
failed to find or open the following file: (ffopen)
/global/project/projectdirs/cosmo/work/legacysurvey/dr8c/ccds-annotated-decam-dr
8.fits.gz
```

>4GB looks suspiciously like a 32-bit memory address limit.

If you have a NERSC account the file should be world readable.  Otherwise ping me offlist and I get get it somewhere that you can see.

**Comment by esheldon** [comment]
Hi Steven.   Can you please make it available by another way?

**Comment by esheldon** [comment]
this works for me on a local file system and gpfs for `1.0.3`

could this be something specific to the nersc file systems or libaries?

**Comment by sbailey** [comment]
Testing locally, I find that it works with 1.0.3 but fails with 0.9.11 (which is also the version we have installed with our software release at NERSC).  So it looks like the answer is for us to upgrade fitsio in our next software release.  We'll test that with our full pipeline and submit any additional bug reports as needed.  Thanks.

**Comment by esheldon** [comment]
ok to close?

**Comment by sbailey** [comment]
yep; thanks
