### ISSUE TITLE
run expandvars on filename in read_header

### ISSUE THREAD

**Issue by esheldon** [esheldon/fitsio#246]

**Comment by esheldon** [comment]
yet another casualty of the `read_header` optimization fiasco

**Comment by beckermr** [comment]
Are you running this on file paths in general? The "pythonic" way has always been to not expand env vars, home tildes etc.

**Comment by esheldon** [comment]
Yes, the code has always run expandvars on the filenames.  See the `extract_filename` function in fitsib.py

Here I am only running expandvars, but should probably be using the fulll `extract_filename` for consistency
