### ISSUE TITLE
Writing comments with blank keywords

### ISSUE THREAD

**Issue by timj** [esheldon/fitsio#249]
At LSST we wish to construct headers that look like this:

```
ORIGIN  = 'LSST DM Header Service'/ FITS file originator

         ---- Date, night and basic image information ----
DATE-OBS=   '2019-10-10T05:40' / Date of the observation (image acquisition)
```

These are fully compliant with the FITS standard where section 4.4.2.4 of https://fits.gsfc.nasa.gov/standard40/fits_standard40aa-le.pdf says:

> Keyword field is blank. This keyword may be used to supply any comments regarding the FITS file. It is frequently used for aesthetic purposes to provide a break between groups of related keywords in the header.

but we can't work out how to call `fitsio` such that we get the blank keyword. Calling `write_key` with an keyword of spaces or a keyword of `None` doesn't work since you either get the blank with an `=` sign, or you get `NONE     =`.  What are we missing?

**Comment by timj** [comment]
I've talked to the cfitsio developers about this and they report that there is no CFITSIO API for handling this scenario but that the suggestion is to form the header card directly with the leading blanks and then add it to the header (the cfitsio API does pad to 80 characters).  This requires you to remember to put the 10 or so leading blanks.

I do wonder if the Python side could be a bit cleverer and use keyword `None` to indicate that you are using blank comments?

**Comment by esheldon** [comment]
I don't think `None` is used in headers currently, so your proposal sounds ok.

It would be pretty easy to implement.  Care to take a crack at it?

**Comment by timj** [comment]
The main impediment to this being that I only used the `fitsio` package for the first time this morning when looking at #250 😄

**Comment by esheldon** [comment]
Understood.  I'll give it a look when I get a chance

**Comment by esheldon** [comment]
In testing the issue #250 I see that in the current code these get converted to COMMENT if you add them as a card, e.g.
```
         ---- Date, night and basic image information ----
```
would end up as
```
COMMENT ---- Date, night and basic image information ----
```

**Comment by esheldon** [comment]
more concretely:
```
hdr = fitsio.FITSHDR()
card = '         ---- Date, night and basic image information ----'
hdr.add_record(card)
```
of course at that point you might as well just add it as a comment.

**Comment by timj** [comment]
The standard says that I can have a comment that doesn't have the word COMMENT in it and I really don't want COMMENT to appear when I'm trying to make the header less cluttered and more readable (I've done this at previous telescopes).  The standard defines three types of comment (COMMENT, HISTORY and "        ").  If you can give me a hint as to where I would look to add knowledge of the third type of comment to the package I can give it a try.

**Comment by esheldon** [comment]
yeah, I understand, I was just explaining what the current behavior is

**Comment by esheldon** [comment]
I had a look and there is no existing mechanism to do this currently.  It does what cfitsio would do which is make it a COMMENT: my comment here indicates cfitsio would take empty keyword and convert to COMMENT https://github.com/esheldon/fitsio/blob/master/fitsio/header.py#L559

we would have to add a special kind of header entry which is "pure card" or something like that, which will write the card rather than writing keyword/value using the standard routines

**Comment by timj** [comment]
Craig Gordon sent me this from cfitsio team:

> One way you can do this is to use the fits_write_record function, where the card string you send it has (at least) the first 8 characters blank followed by your comment.  For example:

```c
char card[50]="        This is just a comment";
fits_write_record(fptr, card, &status);
```
So yes, if you are always parsing header cards before sending them to cfitsio, there will need to be some special logic to bypass this.

**Comment by esheldon** [comment]
exactly what I had in mind, it isn't hard but it means inserting logic for a special case

**Comment by menanteau** [comment]
Sorry to chime in late. I think that the reason why the empty `_________` comments are assigned to `COMMENTS` is because here:
https://github.com/esheldon/fitsio/blob/master/fitsio/header.py#L558
it states that anything without an = and not history is treated as comment

**Comment by esheldon** [comment]
It isn't clear to me we want to insert the `-----`, they are not part of the standard.  @timj can you confirm we just want to add the leading spaces, and it will be up to the user to add cosmetic `----`

**Comment by esheldon** [comment]
indeed @menanteau that is correct

**Comment by timj** [comment]
The standard is talking about the keyword part. The value of the comment starts with position 9 I think (need to check in the standard to be sure -- so long as it is not `=`). The first 8 characters *must* be empty and anything after that is the comment itself. The `----` are my commentary for making things distinctive and are not something you care about -- could be any text. The same thing is true of the completely blank line -- that is an 8 character blank comment and the comment itself is 72 spaces.

**Comment by esheldon** [comment]
thanks

**Comment by esheldon** [comment]
@timj see PR #252
