### ISSUE TITLE
Reading specific elements from binary table column arrays

### ISSUE THREAD

**Issue by mrdoomits** [esheldon/fitsio#25]
When reading columns from a binary FITS table, if a column is actually an array (e.g. the MAG_APER column in SExtractor output is an array of 12 floats) it would be nice to be able to specify particular elements to read, e.g. read only MAG_APER[4].
Thanks!

**Comment by esheldon** [comment]
Sorry I let this one slip.

This would require quite a bit of machinery at the C level to make it work efficiently.

We might be able to this less efficiently by just making a new copy of the array without the extra elements.  This would require extra memory.

Do you feel like taking a stab at this?
