### ISSUE TITLE
How to handle empty lines in header

### ISSUE THREAD

**Issue by NiallMac** [esheldon/fitsio#272]
It seems (some of) the DES images have blank entries in the header e.g.
```
VALIDB  =                    T / Data from amp B is valid                       
NDONUTS =                    0 / AOS number of donuts analyzed for this CCD     
        = '        '           / = '        '           / = '        '          
PHOTFLAG=                    1 / Night Photometric (1) or not (0)               
DESDCXTK= 'Sat Apr 23 02:44:40 2016' / DECam image conversion and crosstalk corr
```
(the line after `NDONUTS`). It's not clear to me how fitsio should handle this; currently the header objects get's an entry with key `None` (in astropy the key is `''`). This was causing issues for some downstream code which expected the keys to be strings, but that's straightforward for me to fix. Anyway, just opening an issue on this after talking with @esheldon, to confirm this is the intended behaviour and/or discuss whether it's worth handling this differently.

**Comment by esheldon** [comment]
It does seem pythonic to leave these as `None`.   What else could it be?  Suggestions anyone?
