### ISSUE TITLE
Incorrect order of comments in header

### ISSUE THREAD

**Issue by demitri** [esheldon/fitsio#277]
Consider this file:

https://dr15.sdss.org/sas/dr15/eboss/photoObj/frames/301/3437/6/frame-g-003437-6-0343.fits.bz2

```python
from fitsio import FITS

filename = "~/frame-g-003437-6-0343.fits"
hdu_list = FITS(filename)
header = hdu_list[0].read_header()
print(header.records()[19])
```

The result of the script above is

```
{'name': 'COMMENT', 'comment': ' CCD-specific parameters', 'value': ''}
```

However, the header record at that position is actually:

```
COMMENT  TAI,RA,DEC,SPA,IPA,IPARATE,AZ,ALT,FOCUS at reading of col 0, row 0
```

Printing out the rest of the header (`print(h.records())`) shows that while the number of `COMMENT` records is correct, the values are all out of order. I looked at the code and it wasn't immediately obvious where the problem was.

**Comment by dstndstn** [comment]
Ugh, I just hit this too.  It seems to be only COMMENT cards, and this problem exists in fitsio 1.1.1 also.

**Comment by demitri** [comment]
Yeah, it sounds like a trivial thing but it was important for what I was doing. I tried to find where the bug was but it wasn't obvious so I moved on. This doesn't seem to be a priority, so I just moved to Astropy.

**Comment by dstndstn** [comment]
Also exists in 1.0.6.  What I was trying to do was update a table, just fixing one column, without changing any headers, etc.

It seems like maybe the very first COMMENT card ends up at the end, and then the rest are cyclically rotated?

**Comment by esheldon** [comment]
I'm sorry this has been on the back burner. fitsio development and maintenance has been slow since covid.  I'll try to have a look at it this week.

**Comment by esheldon** [comment]
@demitri and @dstndstn I've pushed a branch `comment-order` that addresses this

**Comment by esheldon** [comment]
I think this is fixed, so I went ahead and merged.
