### ISSUE TITLE
Evaluating FITS Headers as longlong int errors

### ISSUE THREAD

**Issue by at88mph** [esheldon/fitsio#280]
I have a FPACK'd (.Z) FITS file with keywords like:

```
...
BITPIX  =                   16
QSEQID= 55700500000000068635
...
```

When I slice from that particular HDU, which is a Binary Table, then try to write the decompressed slice out I get this:

```
  File "/src/fitsio/fitsio/fitslib.py", line 624, in write
    header=header)
  File "/src/fitsio/fitsio/fitslib.py", line 680, in write_image
    compress=compress, tile_dims=tile_dims)
  File "/src/fitsio/fitsio/fitslib.py", line 845, in create_image_hdu
    extver=extver)
OSError: FITSIO status = 108: error reading from FITS file
Range Error in ffc2jj converting string to longlong int: 55700500000000068635
Error in ffc2j evaluating string as a long integer: 55700500000000068635
```

I'm trying to trace it through.  Is there somewhere that the datatype is set to instruct `CFITSIO` to perform the conversion incorrectly?

**Comment by esheldon** [comment]
I will convert the code to write long long instead of long.

But note that number is too big to fit into a long long so it still would not work.  The largest integer type cfitsio only supports writing is long long

**Comment by esheldon** [comment]
See #299
