### ISSUE TITLE
Fpack compression stopped working?

### ISSUE THREAD

**Issue by dstndstn** [esheldon/fitsio#283]
Hi,

In fitsio 0.9.12, this code:
```
import fitsio
import numpy as np
img = np.zeros((1000,1000), np.float32)
fitsio.write('/tmp/test.fits.fz[compress R 100,100; qz -1e-4]', img, clobber=True)
```
produces a FITS file that is fpack compressed.

In fitsio 1.0.5, the same code results in a non-compressed file.

Also, `clobber=True` doesn't work in the latter case.

This is in python3, with fitsio installed on a fresh ubuntu 18.04 container using
pip3 install fitsio==0.9.12
or
pip3 install fitsio==1.0.5

cheers,
--dustin

**Comment by dstndstn** [comment]
1.0.2 shows the same behavior as 1.0.5

**Comment by dstndstn** [comment]
Same with 1.0.1

**Comment by dstndstn** [comment]
Down at DESI LegacySurvey.org headquarters, this is forcing us to revert back to 0.9.12

**Comment by esheldon** [comment]
I never even knew that this worked, putting compress information into the filename, it isn't something I ever tested.

**Comment by esheldon** [comment]
the clobber fails because it looks for that filename, including the bracketed information

**Comment by dstndstn** [comment]
The clobber is minor, but the fpack compression is a blocker.

I assume it's just cfitsio doing its Extended Filename thing

**Comment by dstndstn** [comment]
(that used to allow the compression to work, that is)

**Comment by beckermr** [comment]
Ugh. The fits standard has too many features. Supporting everything and making sure it doesn’t break is a pain for sure. :/

**Comment by esheldon** [comment]
In the short term you can keep 1.x (and proper python 3 strings etc) and instead add this information to a header that you write, and then run fpack yourself on it

**Comment by esheldon** [comment]
As for a solution, the right thing to do is probably to just try opening the file with cfitsio and looking for error conditions rather than doing filename processing in python

**Comment by dstndstn** [comment]
It's not really that simple, since we do more fancy stuff: we write the
file to memory, compute a checksum, then write it to disk...

**Comment by esheldon** [comment]
(above was solution for clobber)

a solution for the compression issue is probably something to do with python 3 strings and conversion to a c string in the C code

**Comment by beckermr** [comment]
There is an open issue about using this lib with an in memory file btw. If you have an example of how to do that, can you post it?

**Comment by esheldon** [comment]
the string that's being fed to cfitsio looks fine...  I'm a bit baffled.  Maybe there is a problem with the updated version of cfitsio we are using, or our hacks to cfitsio

**Comment by moustakas** [comment]
@esheldon @beckermr any additional thoughts on this issue? We're a couple short weeks away from launching DR9 (http://legacysurvey.org) and although `0.9.12` doesn't suffer from the fpack compression bug reported here, it has a number of other problems that were fixed in `fitsio/1.0.x`.

**Comment by beckermr** [comment]
I've got nothing here. Can you check cfitsio 3470 at the C level directly? 

Assuming that works, then it is us. Otherwise, we will need to find / patch the bug or rollback the update.

**Comment by beckermr** [comment]
BTW, the version of cfitsio we bundle is here: https://github.com/esheldon/fitsio/tree/master/cfitsio3470

We apply patches to the build from here: https://github.com/esheldon/fitsio/tree/master/patches

So you might also check the actual version we use with patches at the C level as well.

**Comment by esheldon** [comment]
I've been unusually swamped, but I can try to look at this soon
