### ISSUE TITLE
PyPI package out of date (1.0.5)

### ISSUE THREAD

**Issue by rainwoodman** [esheldon/fitsio#287]
Would you update the PyPI package for the 1.0.6 release?

We depend on a bug fix in 1.0.6 but when installing fitsio from pypi the 1.0.5 version does not include the fix: https://github.com/bccp/nbodykit/issues/606.

Thanks!

**Comment by esheldon** [comment]
I cut a new version, v1.1.0 please use that one

**Comment by esheldon** [comment]
@rainwoodman does v1.1.0 work for you?

**Comment by rainwoodman** [comment]
Yes I think so. The latest version is already v1.1.2 on pypi. Is the process for cutting a PyPi release automated?

**Comment by esheldon** [comment]
no, it is not automated.
