### ISSUE TITLE
Header card_string

### ISSUE THREAD

**Issue by astrom-tom** [esheldon/fitsio#293]
Hello!

I have been updating to the last version of fitsio lately and I came across a change with respect to the previous version I have been using for a while (0.9.11):
When using the function class FITS and its method fits_header you used to provide a list of dictionary for each entry in the fits header with a 'card_string' keyword [along with name, comment and value]. I was using this because I could catch a word used ['HIERARCH'] in the fits header keywords that for some reason is not seen.

Do you know if there is a way to mock the behavior of 'card_string' in the new version?

**Comment by esheldon** [comment]
Sorry for the late response on this.  It is probably straightforward to implement.    Would you like to try a fix and make a PR?

**Comment by esheldon** [comment]
@astrom-tom I've got a pull request in that adds back card string
