### ISSUE TITLE
fits header with non ascii keywords gives segmentation fault

### ISSUE THREAD

**Issue by astrom-tom** [esheldon/fitsio#295]
Hello,

in a header I have a line that looks like this:
;Ì�S =              351/ no comment
There is a non ascii keyword there that makes fitsio crash with a segmentation fault. Is there a way to fix it?
Thanks!

**Comment by beckermr** [comment]
Are non-ascii headers actually supported in the FITS standard?

**Comment by astrom-tom** [comment]
well it is a good point, when I open it with astropy it says 

WARNING: non-ASCII characters are present in the FITS file header and have been replaced by "?" characters [astropy.io.fits.util]

but I have a module that uses fitsio (and I love fitsio) and crashed for this type of files. If I remove that line, fitsio works fine.

**Comment by beckermr** [comment]
Right, we'd have to patch `cfitsio` I think. We are already patching in order to support UTF-8 strings in python. IDK how deep we'd have to go to support this too.

**Comment by beckermr** [comment]
@esheldon

**Comment by astrom-tom** [comment]
I can share the file if needed (but  it is 500MB)

**Comment by beckermr** [comment]
yikes - maybe write the headers to a new file?

**Comment by astrom-tom** [comment]
well, I tried that with astropy but it tells me that I can not write this keyword :D 
I have no idea how they create this file originally.

**Comment by beckermr** [comment]
🤦‍♂

**Comment by beckermr** [comment]
did they mean to write this file, or is this file itself buggy?

**Comment by astrom-tom** [comment]
I would guess this one is buggy

**Comment by beckermr** [comment]
K. Then supporting reading it is probably not going to happen. We should fail BETTER, but we may not be able to recover.

**Comment by astrom-tom** [comment]
Yes that would be fine! if there is a Exception raised this would be fine and easy to catch. The segmentation fault makes it just crash.

**Comment by esheldon** [comment]
Can you copy and paste the odd characters with any reliability?  If so we can hand-edit a header for testing

**Comment by astrom-tom** [comment]
The only thing I can extract is this:
;Ì�S =              351 / no comment 
I am afraid I can not get more than that.

**Comment by beckermr** [comment]
We can insert a non-ascii char by hand @esheldon.

**Comment by esheldon** [comment]
you can also use `head -c NBYTES filename` to extract a certain number of bytes

**Comment by esheldon** [comment]
I've tried inserting non ascii characters but I don't get a seg fault, I get a crash with an OSError.

I think I'll need the specific string you have in your header.  Can you try pulling out bytes?

**Comment by dstndstn** [comment]
Hi @esheldon , we're hitting this problem as well.  Obviously going to fix the underlying issue upstream, but if you want a smaller test case:

https://portal.nersc.gov/project/cosmo/temp/dstn/ksb_170321_024825_ood_r_ls9.fits.fz
(1.2 MB)

ext 3 has the bad header; I get

> python -c "import fitsio; fitsio.FITS('ksb_170321_024825_ood_r_ls9.fits.fz')[3].read_header()"
Segmentation fault

I also pulled out just that bad HDU to make a 400k file:

https://portal.nersc.gov/project/cosmo/temp/dstn/bad.fits

and here is just the bad header

https://portal.nersc.gov/project/cosmo/temp/dstn/badhdr

**Comment by esheldon** [comment]
@dstndstn @astrom-tom could you try using the branch nonascii ?

**Comment by dstndstn** [comment]
Hi @esheldon Thanks, I confirm that this works on the example image I sent!
