### ISSUE TITLE
spurious deprecation warnings in v1.1.1

### ISSUE THREAD

**Issue by rmjarvis** [esheldon/fitsio#296]
I'm lately getting some DeprecationWarnings that look like
```
  /anaconda3/envs/py3.7/lib/python3.7/site-packages/fitsio/fitslib.py:440: DeprecationWarning: The keyword arguments '%s' are being ignored! This warning will be an error in a future version of `fitsio`!
    DeprecationWarning)
```
and
```
  /anaconda3/envs/py3.7/lib/python3.7/site-packages/fitsio/hdu/base.py:40: DeprecationWarning: The keyword arguments '%s' are being ignored! This warning will be an error in a future version of `fitsio`!
    DeprecationWarning)
```
and
```
  /anaconda3/envs/py3.7/lib/python3.7/site-packages/fitsio/hdu/table.py:87: DeprecationWarning: The keyword arguments '%s' are being ignored! This warning will be an error in a future version of `fitsio`!
    DeprecationWarning)
```
and more places.

Two problems here.  First, you have a %s, but no `%(str(keys))` in these places, so the %s isn't being filled in.

Second, and more important, I'm pretty sure the logic on these is backwards.  They follow a line `if not keys` which I believe should be `if keys`.  AFAIU, the logic of this is that you don't allow random other keys anymore.  Just the named keyword arguments.  So if there are other kwargs besides what you explicitly allow, then you don't want to allow that anymore.  And it should show a deprecation warning.

But I don't have any kwargs.  So every call to fitsio practically seems to emit this warning.  This seems like an error to me.

**Comment by beckermr** [comment]
I put in a fix for this already I thought.

**Comment by beckermr** [comment]
Yup see here https://github.com/esheldon/fitsio/compare/v1.1.1...master

**Comment by beckermr** [comment]
We need another release to fix it.

**Comment by esheldon** [comment]
I just released v1.1.2 which is available with pip now and with conda shortly

**Comment by beckermr** [comment]
Awesome! closing!

**Comment by rmjarvis** [comment]
Thanks Erin!
