### ISSUE TITLE
Allow BLANK header cards

### ISSUE THREAD

**Issue by CraigLoomis** [esheldon/fitsio#303]
The FITSHDR clean() method removes `BLANK` cards. I don't believe that it should. Unlike NAXISx and BITPIX, the value cannot be recovered from integer image data, which is the only data which BLANK is valid for. 

All the special treatment of BLANK in cfitsio has to do with compression, but that only comes into play when doing lossy compression of integer data. In all other cases BLANK is left alone. [I think the standard says that BLANK _should_ also be used in the case of lossy integer compression, but that ZBLANK is OK.]

I suppose clean() could remove BLANK from headers for floating-point images, but that feels like the wrong place to do that.

**Comment by esheldon** [comment]
Hi Craig.  Thanks for the report.  I'm happy to follow your lead on this.  Would you like to submit a pull request?
