### ISSUE TITLE
Add support for lossless compression of floating point images

### ISSUE THREAD

**Issue by erykoff** [esheldon/fitsio#304]
Currently, `fitsio` does not have support for lossless compression of floating-point images.  I believe this can be turned on with the `fits_set_quantize_level(fits, 0, status))` call in `cfitsio`.

At the same time, it seems that `fitsio` is broken when reading these sorts of compressed images, as illustrated here (because `astropy.io.fits` does support writing in this mode):

```
import astropy.io.fits as fits
import numpy as np
import healpy as hp
import fitsio
cov_index_map = np.arange(1000, dtype=np.int64)
sparse_map_int = np.arange(10000, dtype=np.int32)
sparse_map_int[500: 1000] = np.iinfo(np.int32).min
sparse_map_float = np.arange(10000, dtype=np.float32)
sparse_map_float[500: 1000] = hp.UNSEEN
hdu_list = fits.HDUList()
hdu = fits.PrimaryHDU(data=cov_index_map, header=fits.Header())
hdu_list.append(hdu)
hdu = fits.CompImageHDU(data=sparse_map_float, header=fits.Header(),
                        compression_type='GZIP_2', tile_size=(1000, ),
                        quantize_level=0.0)
hdu_list.append(hdu)
hdu_list.writeto('test.fits', overwrite=True)
sparse_map_in = fits.getdata('test.fits', ext=1)
np.testing.assert_array_almost_equal(sparse_map_in, sparse_map_float)
sparse_map_in = fitsio.read('test.fits', ext=1)
np.testing.assert_array_almost_equal(sparse_map_in, sparse_map_float)
```

(This fails on the final assertion).

**Comment by erykoff** [comment]
I wonder if the reading is due to a cfitsio bug that is fixed in 3.48 https://heasarc.gsfc.nasa.gov/FTP/software/fitsio/c/docs/changes.txt
Specifically:
"Fixed bug in imcompress.c that wasn't properly handling conversion between float and double types when reading from a gzip compressed float or double image."

**Comment by esheldon** [comment]
well, we don't do any type conversions in fitsio so it *shouldn't* matter, but it is certainly worth a try

**Comment by esheldon** [comment]
I tried 3.48, still fails

**Comment by esheldon** [comment]
This is either a bug in cfitsio or a bug in how I'm  using it, I don't think its at the python level

**Comment by esheldon** [comment]
The function `fits_read_pixll` is supposed to read compressed data transparently

**Comment by esheldon** [comment]
Here is the header without setting quantize_level=0
```
XTENSION= 'BINTABLE'           / binary table extension
BITPIX  =                    8 / array data type
NAXIS   =                    2 / number of array dimensions
NAXIS1  =                   32 / width of table in bytes
NAXIS2  =                   10 / number of rows in table
PCOUNT  =                11495 / number of group parameters
GCOUNT  =                    1 / number of groups
TFIELDS =                    4 / number of fields in each row
TTYPE1  = 'COMPRESSED_DATA'    / label for field 1
TFORM1  = '1PB(0)'             / data format of field: variable length array
TTYPE2  = 'GZIP_COMPRESSED_DATA' / label for field 2
TFORM2  = '1PB(1274)'          / data format of field: variable length array
TTYPE3  = 'ZSCALE'             / label for field 3
TFORM3  = '1D'                 / data format of field: 8-byte DOUBLE
TTYPE4  = 'ZZERO'              / label for field 4
TFORM4  = '1D'                 / data format of field: 8-byte DOUBLE
ZIMAGE  =                    T / extension contains compressed image
ZTENSION= 'IMAGE'              / Image extension
ZBITPIX =                  -32 / data type of original image
ZNAXIS  =                    1 / dimension of original image
ZNAXIS1 =                10000 / length of original image axis
ZPCOUNT =                    0 / number of parameters
ZGCOUNT =                    1 / number of groups
ZTILE1  =                 1000 / size of tiles to be compressed
ZCMPTYPE= 'GZIP_2'             / compression algorithm
ZNAME1  = 'NOISEBIT'           / floating point quantization level
ZVAL1   =                 16.0 / floating point quantization level
ZQUANTIZ= 'NO_DITHER'          / No dithering during quantization
EXTNAME = 'COMPRESSED_IMAGE'   / name of this binary table extension
```

Now when setting it to zero it is radically different
```
XTENSION= 'BINTABLE'           / binary table extension
BITPIX  =                    8 / array data type
NAXIS   =                    2 / number of array dimensions
NAXIS1  =                    8 / width of table in bytes
NAXIS2  =                   10 / number of rows in table
PCOUNT  =                 2381 / number of group parameters
GCOUNT  =                    1 / number of groups
TFIELDS =                    1 / number of fields in each row
TTYPE1  = 'COMPRESSED_DATA'    / label for field 1
TFORM1  = '1PB(610)'           / data format of field: variable length array
ZIMAGE  =                    T / extension contains compressed image
ZTENSION= 'IMAGE'              / Image extension
ZBITPIX =                  -32 / data type of original image
ZNAXIS  =                    1 / dimension of original image
ZNAXIS1 =                10000 / length of original image axis
ZPCOUNT =                    0 / number of parameters
ZGCOUNT =                    1 / number of groups
ZTILE1  =                 1000 / size of tiles to be compressed
ZCMPTYPE= 'GZIP_2'             / compression algorithm
ZNAME1  = 'NOISEBIT'           / floating point quantization level
ZVAL1   =                  0.0 / floating point quantization level
ZQUANTIZ= 'NO_DITHER'          / No dithering during quantization
EXTNAME = 'COMPRESSED_IMAGE'   / name of this binary table extension
```

Is this a bug writing the header?

**Comment by erykoff** [comment]
Further investigation shows that there is a bug in `astropy.io.fits` (or at least a fundamental incompatibility with `cfitisio`) in that when there is no quantization, `cfitsio` writes `ZQUANTIZ= 'NONE' into the header while `astropy.io.fits` writes `ZQUANTIZ= 'NO_DITHER`.  According to the `cfitsio` code (if not the FITS convention, which appears to be mute on the subject), reading of unquantized data is only handled properly if `ZQUANTIZ= 'NONE'.
Note that `astropy.io.fits` is able to read unquantized compressed data with either keyword setting.

So I think that we can say that `fitsio` cannot read these malformed `astropy.io.fits` files, and that is fine (and certainly not going to be changed now).  But we still need to add support for changing the `quantize_level` in `fitsio`.

**Comment by esheldon** [comment]
the standard implies that having no `ZQUANTIZ` keyword at all means no quantization is done.  cfitsio also recognizes NONE as equivalent to not quantizing.

The standard also says low q means higher compression, not lower.  This might have been a source of confusion.  So the problem is that in astropy there is no way in astropy to turn off quantization it seems.    It is going to write no dither at a minimum.

**Comment by esheldon** [comment]
setting q = 0 in cfitsio causes it to put ZQUANTIZE='NONE' but I think, to be more pythonic, we should support (and encourage) the use of q=None to imply no quantization

**Comment by esheldon** [comment]
Also note that, while cfitsio takes z=0 as a special value implying no quantization, astropy does not.  The standard implies that q=0 should be perfectly valid, although pointless because it would preserve no information in the resulting compressed image.
