### ISSUE TITLE
Upgrade cfitsio to 3.49

### ISSUE THREAD

**Issue by erykoff** [esheldon/fitsio#308]
The latest version of cfitsio=3.49 (https://heasarc.gsfc.nasa.gov/FTP/software/fitsio/c/docs/changes.txt ) has this fix to reading lossless compressed images:
```
  - Fix to imcompress.c.  It now turns off quantization if ZSCALE
    and ZZERO columns are missing.  Treatment will be the same as
    if ZQUANTIZ were set to 'NONE', even if ZQUANTIZ is present
    and set to something else.
```
Upgrading to this version will allow `fitsio` to read images that were lossless gzip-compressed by `astropy.io.fits` (which turned out to be doing the right, or at least more correct, thing, while cfitsio was wrong.)

**Comment by esheldon** [comment]
we did this
