### ISSUE TITLE
can't configure cfitsio

### ISSUE THREAD

**Issue by esheldon** [esheldon/fitsio#328]
miniconda environment with gcc etc. installed

```
    checking for gcc... gcc
    checking whether the C compiler works... no
```

**Comment by beckermr** [comment]
Can you post the output of conda info and conda list?

**Comment by esheldon** [comment]
conda info
```
     active environment : None
       user config file : /home/esheldon/.condarc
 populated config files : /home/esheldon/.condarc
          conda version : 4.10.0
    conda-build version : not installed
         python version : 3.8.5.final.0
       virtual packages : __cuda=11.2=0
                          __linux=5.4.0=0
                          __glibc=2.31=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /home/esheldon/miniconda3  (writable)
      conda av data dir : /home/esheldon/miniconda3/etc/conda
  conda av metadata url : https://repo.anaconda.com/pkgs/main
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /home/esheldon/miniconda3/pkgs
                          /home/esheldon/.conda/pkgs
       envs directories : /home/esheldon/miniconda3/envs
                          /home/esheldon/.conda/envs
               platform : linux-64
             user-agent : conda/4.10.0 requests/2.24.0 CPython/3.8.5 Linux/5.4.0-77-generic linuxmint/20.1 glibc/2.31
                UID:GID : 1000:1000
             netrc file : /home/esheldon/.netrc
           offline mode : False

```

**Comment by esheldon** [comment]
[conda-list.txt](https://github.com/esheldon/fitsio/files/7122228/conda-list.txt)

**Comment by beckermr** [comment]
Hmmmmm. Can you print the output of the log file that autotools makes? I forget the name.

**Comment by esheldon** [comment]
[config.log](https://github.com/esheldon/fitsio/files/7122327/config.log)

**Comment by beckermr** [comment]
It looks like the linker is failing to find pthreads. IDK how that is possible, but this appears to be a local issue. You should check to make sure your system has the lib in the standard spots and you are not forcing LD_LIBRARY_PATH.

**Comment by esheldon** [comment]
Note if I just cd into that directory I can configure fine, it is only when configuring via setup.py

**Comment by beckermr** [comment]
maybe it is the subprocess call then. Let's make sure we are using shell=True there.

**Comment by esheldon** [comment]
we are

**Comment by beckermr** [comment]
Try without the `sh` too.

**Comment by esheldon** [comment]
Yeah, I did.  Also tried explicitly `bash`

**Comment by beckermr** [comment]
hmmm. I cannot reproduce at BNL, so you'll need to do more debugging. There is an env var you can set that shows what the linker is doing, maybe LD_DEBUG or something. Set that and see what happens. I might have the wrong env var btw so def google it first.

**Comment by beckermr** [comment]
My configure output shows the full path to the compiler, 

```
/gpfs02/astro/workarea/beckermr/miniconda3/envs/fitsio-dev/bin/x86_64-conda-linux-gnu-cc
```

not gcc. This may be related.

**Comment by esheldon** [comment]
setting CC to the full path doesn't help

(note this is on my home machine with ubuntu)

**Comment by esheldon** [comment]
I tried a different env and it works, so maybe my base environment is borked

**Comment by beckermr** [comment]
hmmm I cannot reproduce in my base env at BNL - glad you got something working!
