### ISSUE TITLE
make reading single row or column from image work more naturally

### ISSUE THREAD

**Issue by esheldon** [esheldon/fitsio#33]
The slice notation

```python
with FITS(filename) as fits:
    sub = fits[0][ rowbeg:rowend, colbeg:colend ]
```
doesn't work for a singleton

```python
with FITS(filename) as fits:
    # causes an error
    sub = fits[0][ row, colbeg:colend ]
```
make this case work as welll

**Comment by dnelson86** [comment]
Just ran into this as well, nothing a little

```
sub = fits[0][ row:row+1, colbeg:colend ]
sub = np.squeeze(sub)
```

won't fix, but yes it would be nice.

**Comment by esheldon** [comment]
I recently pushed a change to master to fix this.

It no longer causes an error to do this
```python
fits[0][row, colbeg:colend]
```

However, I have thus far elected *not* to call squeeze() on the result be default, because the user may have used row:row+1 on *other* dimensions, indicating they want those length one dimension preserved.  Figuring out a simple way to do this all correctly is a further *TODO*

**Comment by esheldon** [comment]
The logic for this is too complicated to deal with all cases, I'm going to close for now
