### ISSUE TITLE
change filling of bad characters in header keywords

### ISSUE THREAD

**Issue by esheldon** [esheldon/fitsio#331]
currently filling with `JUNK____....`

**Comment by esheldon** [comment]
@beckermr @dstndstn

**Comment by beckermr** [comment]
:/ no good options here unless we change the length of the keyword, which is a huge pain in C

**Comment by esheldon** [comment]
We could fill with `?` so it is obvious that something wasn't right

**Comment by esheldon** [comment]
That would not be legal FITS but it would signify a problem

**Comment by esheldon** [comment]
interesting:  if you put a `?` in a keyword and write that using fitsio (cfitsio) it makes a heiararch keyword for it, even if it is short, and preserves the `?`

**Comment by beckermr** [comment]
I thought that would cause a segdault elsewhere but now I'm thinking I'm wrong about that. 

I'm good with a question mark.

**Comment by beckermr** [comment]
I also think a # would be ok.

**Comment by esheldon** [comment]
this is odd; using the latest master
```python
import numpy as np
import fitsio

hdr = {'bla?rg': 3}

data = np.zeros(10)

fitsio.write('test.fits', data, header=hdr, clobber=True)

hin = fitsio.read_header('test.fits')
print(hin)
```
gives
```
Traceback (most recent call last):
  File "test.py", line 10, in <module>
    hin = fitsio.read_header('test.fits')
  File "/home/esheldon/miniconda3/envs/stack/lib/python3.8/site-packages/fitsio/fitslib.py", line 238, in read_header
    return FITSHDR(_fits.read_header(hdunum))
OSError: FITSIO status = 202: keyword not found in header
Warning: the following keyword does not conform to the HIERARCH convention
HIERARCH BLA?RG =            3
```

**Comment by esheldon** [comment]
Note using `bla.rg` doesn't raise an error, so this dot must be a special case

**Comment by beckermr** [comment]
I am so confused.

**Comment by beckermr** [comment]
I guess we should allow . For only hierarch per @dstndstn's pr or similar?

**Comment by beckermr** [comment]
Or we can bite the bullet and use an _ everywhere. That is expected.

**Comment by esheldon** [comment]
well, in any case don't we need to revisit the PR to figure out why this didn't get converted internally to something OK?

**Comment by beckermr** [comment]
I think cfitsio is interpreting any non-ascii as a hierarch when it writes and this breaks our read in another spot. The output fits file has:

```
HIERARCH BLA?RG =            3 
```

AFAIK, we did not intend to write a hierarch keyword. 

This would indicate that for simple headers on write, any non-conforming key characters need to be cast to `_`. On read, we do the same, unless the keyword is hierarch, and then we also allow `.` and convert anything else to `_`.

**Comment by beckermr** [comment]
Or we only allow proper reads / writes of hierarch, do no casting on write, minimal casting on read, and this force everyone to play by the rules. That's probably better.

**Comment by dstndstn** [comment]
I still believe that your strict reading of "the rules" (the HIERARCH description), such as they are, is too strong :)  I would argue that the paragraph describing the ESO implementation is a description, not a prescription; I think the HIERARCH keyword parsing should be as liberal as possible without causing issues elsewhere.  Certainly including "." in the allowed characters (for HIERARCH headers only) doesn't seem like a risk.

**Comment by dstndstn** [comment]
(apologies for my previous (now deleted) comment - I see your #332 does exactly what I would like!  Thank you!!)

**Comment by beckermr** [comment]
One more idea here. It turns out any keyword character besides #, * and ? is allowed since FITSIO will simply write and read as HIERARCH if needed. So maybe we just turn off translation of any weird characters? 

This would have a side effect of the same fits file keywords which are non-HIERARCH being put back out as HIERARCH in some cases.

**Comment by beckermr** [comment]
Ignore my previous comment.

**Comment by beckermr** [comment]
I have been thinking again on this and we could remove most of the junk character replacement except for `*`, `?` and `#`. Is this worth it?

**Comment by esheldon** [comment]
Do you mean allow any ascii characters other than those when reading?

**Comment by beckermr** [comment]
Yeah we can parse if we force strings
