### ISSUE TITLE
Updating an existing record in an image header raises an exception

### ISSUE THREAD

**Issue by ussegliog** [esheldon/fitsio#337]
I wish to update a existing record but an error occurs : `IndexError: list assignment index out of range` on self._record_list

In my opinion, this problem is due to a previous record delete. I'm trying to remove some keywords before updating an existing record. The update raises the exception.

Here, my code to reproduce my problem with a fits file as input : [fitsio_headers.txt](https://github.com/esheldon/fitsio/files/7570211/fitsio_headers.txt)
I'm just reading the first image extension header, adding a new record, deleting some keywords and overriding the previous record.
I've got the exception if I use the delete function and retrieve the same FITSHDR reference. However, if I build a new FITSHDR instance and keep only what I want, that works.

Perhaps I'm simply doing something wrong by delete the records.

I'm using  fitsio 1.0.5.

**Comment by esheldon** [comment]
I agree this is most likely a bug which we should track down.

But can I ask why you want to delete those?  You can write a header with those in place, fitsio will remove reserved keywords internally for you.

You can also use `hdr.clean()` to remove reserved keywords.

**Comment by ussegliog** [comment]
Thanks for the hint. I will try `hdr.clean()`.
I had a problem with BZERO keyword with a rescaling applied during reading/writing.Thus, in order to avoid that problem and keep only what it really uses, I decided to remove those. 

Also, I have to remove other keywords (some user keywords). Do I have to build a new FISTHDR to prevent the bug? Is there any other way?

**Comment by esheldon** [comment]
First would it be possible to try a newer version of fitsio?

I won't get to exploring this bug for a few days.

**Comment by ussegliog** [comment]
I tried with 1.1.5 version (from master). I've got the same problem.

I think, I know what it is. Here a simple patch to fix my test : [list_assignment_index_out_of_range.txt](https://github.com/esheldon/fitsio/files/7580630/list_assignment_index_out_of_range.txt)

**Comment by esheldon** [comment]
I see from your patch what the bug is, thanks.  Do you want to submit a pull request and add a unit test that reflects your use case?

**Comment by ussegliog** [comment]
Let me know if there is a problem with the PR.
