### ISSUE TITLE
Feature request: allow setting the FPACK dither seed

### ISSUE THREAD

**Issue by dstndstn** [esheldon/fitsio#351]
Hi,

I'm trying to make it so my code writes bit-identical outputs every time it runs, but I'm using the compression schemes that do the subtractive dither thing, so there is a seed chosen at run-time.  It looks like CFITSIO has routines to set that seed -
`fits_set_quantize_dither()` or `fits_set_dither_seed()` etc
https://heasarc.gsfc.nasa.gov/docs/software/fitsio/c/c_user/node41.html

It looks like one place to add this feature would be here,
https://github.com/esheldon/fitsio/blob/c8f8d608efbbc304ff58c9e005a1f382b61abfef/fitsio/fitsio_pywrap.c#L1376
ie similar to how the quantization level can be set,
https://github.com/esheldon/fitsio/blob/c8f8d608efbbc304ff58c9e005a1f382b61abfef/fitsio/fitsio_pywrap.c#L1483

thanks!
-dustin

**Comment by esheldon** [comment]
Good idea Dustin. Do you want to take a shot at it?

**Comment by dstndstn** [comment]
Maybe :)  this isn't at the top of the priority stack at the moment though...
