### ISSUE TITLE
Writing a new file with compressed data with only 1 entry

### ISSUE THREAD

**Issue by pootle** [esheldon/fitsio#355]
I'm trying to take an existing file, update some header fields and then save old data with updated header to a new file with compression. Using compression, the file has 2 HDUs, the first is empty, but confuses other apps.
```
import fitsio
import numpy as np

fitsio.write
('testout.fits', np.zeros((5,4)), clobber=True, compress='GZIP_2')
checkfits = fitsio.FITS('testout.fits')
print('all at once', len(checkfits))
print(checkfits[0].read())
checkfits.close()
fitsio.write('testout.fits', np.zeros((5,4)), clobber=True)
checkfits = fitsio.FITS('testout.fits')
print('all at once no compression', len(checkfits)) 
checkfits.close()
```

gives

```
all at once 2
None
all at once no compression 1
```

I have tried using 
```
afits = fitsio.FITS('testout.fits', 'rw')
...
```
but I can only set compression by calling afits.write(...) which creates another HDU

**Comment by esheldon** [comment]
Thanks for the report.  Looks like the write works, but the object is not being updated after write.  It works after leaving a context, see below
```python
import fitsio
import numpy as np

data = np.random.uniform(size=(5, 4))

for comp in (None, 'GZIP_2'):
    print('-' * 70)
    print(f'testing compress {comp}')
    fname = f'test-{comp}.fits'
    with fitsio.FITS(fname, 'rw', clobber=True) as fits:
        fits.write(data, compress=comp)
        print('test from object')
        rdata = fits[0].read()
        print(rdata)
        if rdata is not None:
            assert np.all(rdata == data)
        else:
            print('is None')

    print('test after close')
    rdata = fitsio.read(fname)
    assert np.all(rdata == data)

```

**Comment by beckermr** [comment]
2 hdus with compression is expected. That's how the tile compressed image standard is implemented in fits.

**Comment by pootle** [comment]
Ah!, must be software that can't cope with compressed files then - or I confused it somehow, I'll have another go!
thanks very much.

**Comment by esheldon** [comment]
There is still the issue that the fits object isn't being updated after the write

**Comment by esheldon** [comment]
actually never mind, this is the same thing, due to data being in the second hdu
