### ISSUE TITLE
Problem reading boolean column from table

### ISSUE THREAD

**Issue by gbernstein** [esheldon/fitsio#39]
I have a boolean column in a FITS table (written using fitsio).  They all seem to be read back as False using fitsio but look ok when read by astropy.io.fits.

**Comment by esheldon** [comment]
@dstndstn reading bool columns seems to have broken recently.  Not sure what happened.

**Comment by esheldon** [comment]
@dstndstn is this an issue you could take a look at?  I'm not that familiar with boolean stuff you added

**Comment by dstndstn** [comment]
Yes, I've been meaning to have a look at this.

**Comment by rainwoodman** [comment]
Apparently it is broken on Edison all the way to v0.9.6; but on my computer all versions seem to be OK.

**Comment by rainwoodman** [comment]
It is related to the version of numpy. But using astype to cast the view of an array is wrong. As type tries to preserve the semantic but view preserves the underlining representation. 

This wasn't captured by the test suite , for the test cases used 'b' rather the the correct '?' for the booleans. I've updated the test case as well.

**Comment by dstndstn** [comment]
Interesting... so is there a better call to use than astype()?  Or do we
have to do some array.data wrangling?

​

**Comment by esheldon** [comment]
@dstndstn I'm looking at the pull request #43 where @rainwoodman uses a view instead of astype

**Comment by dstndstn** [comment]
Ok, sounds reasonable.

**Comment by esheldon** [comment]
I'm going to merge #43 .  Please everyone test it well!

**Comment by esheldon** [comment]
reopened since we need to test.

By the way @rainwoodman should the other tests be '?' too, e.g.

('b1vec','b',nvec)
and
('b1arr','b',ashape)

What about 'b', is it not appropriate?  Should we document that in the README.md?

**Comment by dstndstn** [comment]
Just want to highlight that the FITS logical datatype contains the ASCII
characters 'T' and 'F', not binary 0 and 1.  I don't know that that is
really tested here, and that feels a little different than the other
datatypes where the encodings are unambiguous (other than being
big-endian!).

**Comment by esheldon** [comment]
I'm looking at the test @rainwoodman 

for t=='b1' we have the following in the test data

data[t+'scalar'] = (numpy.arange(nrows) % 2 == 0).astype(t)

is that correct?  Should it not be '?'

**Comment by esheldon** [comment]
@dstndstn OK, I don't fully understand this data type, I could use some advice from you guys regarding that

**Comment by rainwoodman** [comment]
Well you may find this interesting:

print '\n'.join([str((i, numpy.dtype(i))) for i in ['b1', 'b', '?']])
('b1', dtype('bool'))
('b', dtype('int8'))
('?', dtype('bool'))

so 'b' does not seem to be a consistent type char. 

I am not sure if the consensus is to use 'b1' or '?', but my preference is '?'. 

I do recall '?' had an issue with the python buffer interface in numpy 1.6.x or so; but it should have been fixed long time ago. That bug may be why 'b1' was used in the old code.

**Comment by rainwoodman** [comment]
And b2 becomes int8 as well!

print '\n'.join([str((i, numpy.dtype(i))) for i in ['b2', 'b1', 'b', '?']])
('b2', dtype('int8'))
('b1', dtype('bool'))
('b', dtype('int8'))
('?', dtype('bool'))

**Comment by rainwoodman** [comment]
@dstndstn 

I am not sure if the following sentence is human-parseable: 

fitsio parses data in fits boolean representation (T/F) and returns data in numpy boolean representation contained in a numpy array, on-the-fly as the read request is resolved.

**Comment by rainwoodman** [comment]
Since this but affects reading DECALS DR1 catalogue, which is already semi-released, I would urge for a release after we confirm it has been fixed.

**Comment by esheldon** [comment]
I want to hear from @gbernstein  that his problem is fixed using master, and hopefully @dstndstn will sign off as well

**Comment by gbernstein** [comment]
Not sure I'll get to do the check today but I'll try to get it done soon.  We will also probably want to pull the new release into DESDM.

**Comment by gbernstein** [comment]
Current master branch does pass a simple test for me (Anaconda python, Mac OS10.9.5, with python 2.7.9, numpy 1.9.2) where the older release failed.

**Comment by esheldon** [comment]
This should be fixed now in master.
