### ISSUE TITLE
1.2.2 on pypi?

### ISSUE THREAD

**Issue by olebole** [esheldon/fitsio#396]
Hi Eric,

it seems that the latest fitsio 1.2.2 is not on [PyPI](https://pypi.org/project/fitsio/) yet?

Cheers

Ole

**Comment by esheldon** [comment]
I was going to release it on pypi today if it successfully went through on conda forge, but it hasn't yet for some reason it don't understand.

**Comment by esheldon** [comment]
1.2.2 uploaded to pypi

**Comment by olebole** [comment]
Dankeschön :grin:

**Comment by esheldon** [comment]
Gerne
