### ISSUE TITLE
Please consider creating a Debian/Ubuntu package

### ISSUE THREAD

**Issue by olebole** [esheldon/fitsio#40]
Hi,

I just read about python-fitsio on the [astropy mailing list](http://mail.scipy.org/pipermail/astropy/2015-April/003715.html), and I wonder if you would like to create Debian/Ubuntu package?

Ideally, this should be done within the [Debian Astronomy Working group ](https://lists.debian.org/debian-astro/). You could do it yourself, or anyone else can volunteer. As far as I investigated the package, the Debian package creation would be quite easy, so this can even be a task for a beginner.

The only change to the source code I would see now is to build it against the cfitsio library [provided by Debian](https://packages.debian.org/source/unstable/cfitsio) (which is version 3370 in the moment). There is already a pull request #27 for this. @esheldon the package require to be linked to some minimal cfitsio version, so we can make sure that all features are supported.

Please contact me directly, or via the [mailing list](mailto:debian-astro@lists.debian.org) if you need further information. We can guide you through the full process, and also finally upload your package to Debian. Once it is in Debian, it will automatically migrate to Distributions like Ubuntu or Mint.

Best regards

Ole

**Comment by esheldon** [comment]
This is a good idea.  I don't have any experience with debian packaging, and I don't know how much time I could spend on it as I'll be unavailable for about a month starting approximately next week.  But I am happy to answer questioins

As for using a system cfitsio.  As you noted, @beckermr has suggested something similar.

I think this is a perfect example of when using the system cfitsio is a good idea, so we should probably figure out how to merge that code.  I still would prefer the feature is not on by default, as most cfitsio installs are out of data.

**Comment by esheldon** [comment]
use of the system cfitsio is now supported through the --use-system-fitsio flag.  It will be required that the system version is >= the bundled version.  Note some features are in fitsio but not in the upstream, currently bzip2 is an example.

Anyone want to take a shot at the packages?

**Comment by olebole** [comment]
Thank you very much! 
It would be nice if someone could volunteer here. We will help with all questions that may arise.

**Comment by olebole** [comment]
I am going to package it: ["Intend To Package" bug report](https://bugs.debian.org/820811)

**Comment by olebole** [comment]
There are currently two tests to fail with the system provided cfitsio (version 3380): one is the missing bzip2 compression, and the other is that tile compression does not work with data type `u2`.
Did you report these problems (especially the second one) to the cfitsio authors?

**Comment by olebole** [comment]
Since we have [fitsio in Debian](https://packages.debian.org/source/sid/python-fitsio), I am going to close the issue.

**Comment by esheldon** [comment]
Did you do the work to get fitsio in debian?

If so, thank you, and please let me know if you need any coordination with fitsio releases.

**Comment by olebole** [comment]
Yes, I did it (already a while ago...). In the moment, the package is fine, so there is nothing to be done. I will come if there is anything where I need assistance (and I will ofcourse forward bugs that relate to the sources). Please let me however also know if there are important changes on the horizon (inclusion into astropy or such).
Thank you for your help!
