### ISSUE TITLE
CFITSIO changed license: incompatible with GPL

### ISSUE THREAD

**Issue by olebole** [esheldon/fitsio#402]
Starting with version 4.4.0. cfitsio changed its license to the "NASA Open Source Agreement" 1.3. While this license is OSI approved, Debian and GNU consider it as non-free. Aside from that it is not combinable with the GPL, which is the license of the Python fitsio package.

There already is addressed to HEASARC; however it may be useful that they know about the affected projects. Until this is resolved, I would recommend to stay with cfitsio 4.3.0.

(For the Debian package it does not matter, since we don't use the cfitsio provided with your package, but link to Debians cfitsio lib, which stays at 4.3.0 because of the licensing problems).

**Comment by esheldon** [comment]
I'm OK relicensing as long as the license is free.

**Comment by olebole** [comment]
I guess that is the problem here: From the GNU and Debian point of view, cfitsio isn't free anymore. I think that we cannot include cfitsio unless they revert the license change. If you would change to the NASA license, Debian also couldn't include your fitsio.

IMO the only way out here is to convince HEASARC to make a license change; everything else is desastrous for the astronomy community. cfitsio is one of the basic building blocks here.

**Comment by esheldon** [comment]
agreed

**Comment by esheldon** [comment]
We could bring this up on the cfitsio github page.  I think we would need to be able to link to the debian email list or forum where this was discussed.

**Comment by esheldon** [comment]
Mr. Streicher do you know which part of the license makes it non free?

**Comment by olebole** [comment]
@lpsinger already contacted them to resolve. There is a [comment on the GNU license page](https://directory.fsf.org/wiki/License:NASA-1.3) stating that the paragraph

> G. Each Contributor represents that that its Modification is believed to be Contributor's original creation and does not violate any
existing agreements, regulations, statutes or rules, and further that Contributor has sufficient rights to grant the rights conveyed by this Agreement.

makes it non-free because it does not allow f.e. to incorporate a software snippet from somewhere else (even when covered by a free license) into a NOSA licensed software.

**Comment by beckermr** [comment]
Specifically, the only issue is the "Contributor's original creation" clause I think.

**Comment by lpsinger** [comment]
@trjaffe, is it true that you have decided to revert to the original license for the next release of cfitsio?

**Comment by trjaffe** [comment]
Yes, we will be putting out a new release soon with the original license.  Apologies for the confusion.

**Comment by bryanirby** [comment]
The CFITSIO main & master branches were updated for that [new release](https://github.com/HEASARC/cfitsio/branches) (v4.4.1) last week.  Also tagged with cfitsio4_4_1.

**Comment by olebole** [comment]
Specifically https://github.com/HEASARC/cfitsio/commit/fed49d057bddef5b659bb9f344ffdd73c49a05c6
That looks great! Thank you very much!

**Comment by esheldon** [comment]
Yes, thank you

**Comment by esheldon** [comment]
See #404

**Comment by esheldon** [comment]
The new release 1.2.4 has cfitsio with updated license
