### ISSUE TITLE
strings read from binary tables should have spaces replaced will \0s

### ISSUE THREAD

**Issue by erykoff** [esheldon/fitsio#42]
If you start with a numpy string column with null padded strings, this is written to file with trailing spaces (as per the fits standard, these nulls are replaces with spaces).  

However, when reading in the file from a binary table all the strings now have trailing spaces, but these should be replaced with \0s.  

```
import fitsio
import numpy as np
test=np.zeros(2,dtype=[('A','S10')])
test['A']='hello'
print test
fitsio.write('testbin.fit',test,clobber=True)
test2=fitsio.read('testbin.fit',ext=1)
print test2
```

This results in:
```
[('hello',) ('hello',)]
[('hello     ',) ('hello     ',)]
```

Note that (a) this works with ascii tables, and (b) this works with pyfits.  (I also note that on writing pyfits replaces all trailing spaces with \0s which is not standard fits, but results in binary tables that aren't space-padded with fitsio!)  

Fixing this looks to be a bit of a challenge.  Since the binary tables are read in through direct copying binary data into memory (for speed), there is no chance to replace the spaces with built-in cfitsio string reading routines. Yet, it does result in undesirable behavior.

**Comment by esheldon** [comment]
cfitsio does not follow the standard here.  I've tried to fix it up by hacking cfitsio but then lots of things break.

This is a difficult one

**Comment by esheldon** [comment]
Definitely not going to get help from cfitsio here.  I'm not sure how we could possibly make this work, since cfitsio internally removes the '\0' and pads with spaces.

the only recourse, I think, is to use variable length strings.  These are stored as type 'O' in the numpy structured array

**Comment by esheldon** [comment]
OK to close since we don't have a path to fixing this?

**Comment by erykoff** [comment]
sure.
