### ISSUE TITLE
fitsio-v0.9.7 Windows install problem (pip or setup.py)

### ISSUE THREAD

**Issue by ajamyajax** [esheldon/fitsio#47]
Collecting fitsio
  Using cached fitsio-0.9.7.tar.gz
    Complete output from command python setup.py egg_info:
    'sh' is not recognized as an internal or external command,
    operable program or batch file.
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "C:\myuserpath\AppData\Local\Temp\pip-build-tm1tpw_t\fitsio\setup.py", line 62, in <module>
        configure_cfitsio()
      File "C:\myuserpath\AppData\Local\Temp\pip-build-tm1tpw_t\fitsio\setup.py", line 42, in configure_cfitsio
        raise ValueError("could not configure cfitsio %s" % cfitsio_version)
    ValueError: could not configure cfitsio 3370

**Comment by esheldon** [comment]
I need help from windows folks with this one.  Anyone got a windows box and can look at this?

**Comment by kgage** [comment]
The windows command line doesn't accept 'sh ./configure' as a valid command (setup.py line 40 in configure_cfitsio), but that part can be worked around by using a client such as cygwin to execute linux commands.
Even with the workaround; however, when I try to install I get

$ pip install fitsio
Collecting fitsio
  Using cached fitsio-0.9.7.tar.gz
Requirement already satisfied (use --upgrade to upgrade): numpy in c:~anaconda2\lib\site-packages (from fitsio)
Building wheels for collected packages: fitsio
  Running setup.py bdist_wheel for fitsio
  Complete output from command C:~\Anaconda2\python.exe -c "import setuptools;__file__='c:\\cygwin\\tmp\\pip-build-rkw71v\\fitsio\\setup.py';exec(compile(open(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" bdist_wheel -d c:\cygwin\tmp\tmpzewfqcpip-wheel-:
  make[1]: Entering directory '/tmp/pip-build-rkw71v/fitsio/build/cfitsio3370'
  make[1]: Nothing to be done for 'stand_alone'.
  make[1]: Leaving directory '/tmp/pip-build-rkw71v/fitsio/build/cfitsio3370'
  running bdist_wheel
  running build
  running build_py
  creating build\lib.win-amd64-2.7
  creating build\lib.win-amd64-2.7\fitsio
  copying fitsio\fitslib.py -> build\lib.win-amd64-2.7\fitsio
  copying fitsio\test.py -> build\lib.win-amd64-2.7\fitsio
  copying fitsio\util.py -> build\lib.win-amd64-2.7\fitsio
  copying fitsio\__init__.py -> build\lib.win-amd64-2.7\fitsio
  running build_ext
  building 'fitsio._fitsio_wrap' extension
  creating build\temp.win-amd64-2.7
  creating build\temp.win-amd64-2.7\Release
  creating build\temp.win-amd64-2.7\Release\fitsio

before the command console becomes a wall of text filled with warnings and errors. It then goes through another block:

  error: command 'C:~\\AppData\\Local\\Programs\\Common\\Microsoft\\Visual C++ for Python\\9.0\\VC\\Bin\\amd64\\cl.exe' failed with exit status 2

  ----------------------------------------
  Failed building wheel for fitsio
Failed to build fitsio
Installing collected packages: fitsio
  Running setup.py install for fitsio
    Complete output from command C:~\Anaconda2\python.exe -c "import setuptools, tokenize;__file__='c:\\cygwin\\tmp\\pip-build-rkw71v\\fitsio\\setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record c:\cygwin\tmp\pip-9yul5w-record\install-record.txt --single-version-externally-managed --compile:
    make[1]: Entering directory '/tmp/pip-build-rkw71v/fitsio/build/cfitsio3370'
    make[1]: Nothing to be done for 'stand_alone'.
    make[1]: Leaving directory '/tmp/pip-build-rkw71v/fitsio/build/cfitsio3370'
    running install
    running build
    running build_py
    creating build\lib.win-amd64-2.7
    creating build\lib.win-amd64-2.7\fitsio
    copying fitsio\fitslib.py -> build\lib.win-amd64-2.7\fitsio
    copying fitsio\test.py -> build\lib.win-amd64-2.7\fitsio
    copying fitsio\util.py -> build\lib.win-amd64-2.7\fitsio
    copying fitsio\__init__.py -> build\lib.win-amd64-2.7\fitsio
    running build_ext
    building 'fitsio._fitsio_wrap' extension

Then another wall of warnings and errors after which I get the ending error code bit again.

    error: command 'C:~\\AppData\\Local\\Programs\\Common\\Microsoft\\Visual C++ for Python\\9.0\\VC\\Bin\\amd64\\cl.exe' failed with exit status 2

    ----------------------------------------
Command "C:~\Anaconda2\python.exe -c "import setuptools, tokenize;__file__='c:\\cygwin\\tmp\\pip-build-rkw71v\\fitsio\\setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record c:\cygwin\tmp\pip-9yul5w-record\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in c:\cygwin\tmp\pip-build-rkw71v\fitsio



Some example error messages include the following:
  fitsio/fitsio_pywrap.c(594) : error C2143: syntax error : missing ';' before 'type'
  fitsio/fitsio_pywrap.c(595) : error C2143: syntax error : missing ';' before 'type'
  fitsio/fitsio_pywrap.c(596) : error C2275: 'LONGLONG' : illegal use of this type as an expression
          c:\cygwin\tmp\pip-build-rkw71v\fitsio\cfitsio3370\fitsio.h(132) : see declaration of 'LONGLONG'
  fitsio/fitsio_pywrap.c(596) : error C2146: syntax error : missing ';' before identifier 'dims'
  fitsio/fitsio_pywrap.c(596) : error C2065: 'dims' : undeclared identifier
  fitsio/fitsio_pywrap.c(596) : error C2109: subscript requires array or pointer type
  fitsio/fitsio_pywrap.c(608) : error C2065: 'maxdim' : undeclared identifier
  fitsio/fitsio_pywrap.c(608) : error C2065: 'ndims' : undeclared identifier
  fitsio/fitsio_pywrap.c(608) : error C2065: 'dims' : undeclared identifier

Both walls of text seem to be the same wall at a glance with approximately 80 errors per wall of text (not counting warnings).

**Comment by esheldon** [comment]
We still need some more eyes on the windows front.  Is anyone able to take a more detailed look at this?

**Comment by esheldon** [comment]
I'm going to close this, but generally we need help on the windows side.   I would be interested to see if the newer fitsio are doing any better here.

**Comment by ajamyajax** [comment]
Hi Eric,

Well, the latest fitsio package still does not install on Windows, at least
for me.  And I did my best to fiddle with it too, but couldn't work around
the linux shell scripting.

If you really want to get this working you might ask this fellow for
assistance, who seems to be a wiz at making packages Windows compatible:

"Unofficial Windows Binaries for Python Extension Packages"
by Christoph Gohlke, Laboratory for Fluorescence Dynamics, University of
California, Irvine.

http://www.lfd.uci.edu/~gohlke/pythonlibs/

Best of luck, Mark

**Comment by ajamyajax** [comment]
Sorry... Erin!
