### ISSUE TITLE
Column slicing issues

### ISSUE THREAD

**Issue by kgage** [esheldon/fitsio#56]
When attempting the following code
```
import fitsio
f = fitsio.FITS('spec-3874-55280-0067.fits')
clolumn = f[2]['SUBCLASS']
```
column is returned as
```
file: ~/spec-3874-55280-0067.fits
  extension: 2
  type: BINARY_TBL
  rows: 1
  column subset:
    CLASS               S6  array[6]
    SUBCLASS           S21  array[21]
    U                   f4  array[5]
    L                   f8  
    B                   f8  
```
and attempting to take column[:] crashes iPython.

If I use
```
columns = f[2]['CLASS','SUBCLASS']
```
returns
```
file: ~/spec-3874-55280-0067.fits
  extension: 2
  type: BINARY_TBL
  rows: 1
  column subset:
    CLASS               S6  array[6]
    SUBCLASS           S21  array[21]
```
and columns[:] works fine in this case.

It looks like when specifying a single column, fitsio searches for any subset of the given column name.

**Comment by esheldon** [comment]
This works for me.  What version of fitsio are you using?

**Comment by kgage** [comment]
init module says version is 0.9.7

I already tried upgrading to see if that would work.
```
~$ pip install fitsio --upgrade
Requirement already up-to-date: fitsio in ./anaconda/lib/python2.7/site-packages
Requirement already up-to-date: numpy in ./anaconda/lib/python2.7/site-packages (from fitsio)
```

**Comment by esheldon** [comment]
OK, I'm not sure then.  Can you try working from the master branch?

**Comment by esheldon** [comment]
Also, do you mind making a fits file available that causes the problem?

**Comment by kgage** [comment]
I cloned and used version '0.9.8rc1' and this did not have any effect.
The fits file I am using can be downloaded from the SDSS website:
data.sdss3.org/sas/dr12/boss/spectro/redux/v5_7_0/spectra/lite/3874/spec-3874-55280-0067.fits

**Comment by esheldon** [comment]
OK, think it has to do with string fields.

I'll check it out.

**Comment by esheldon** [comment]
Please give it a try

**Comment by esheldon** [comment]
Note the fix is in the master branch.  I've tested it works on my linux boxes

**Comment by kgage** [comment]
This fix works for me as well, thanks.
