### ISSUE TITLE
Segfault reading ASCII table

### ISSUE THREAD

**Issue by kbarbary** [esheldon/fitsio#57]
To reproduce:

```
wget -O table1.fits http://cdsarc.u-strasbg.fr/viz-bin/nph-Cat/fits?J%2FApJ%2F686%2F749/table1.dat
```

```python
import fitsio
fitsio.read("table1.fits", ext=1)
```

Doesn't segfault every time, just most times.

fitsio v0.9.7, Python 3.4 (anaconda), Linux.

**Comment by esheldon** [comment]
I also see this on my machine.

**Comment by esheldon** [comment]
This fits file is using some parts of the standard I didn't even know existed, such as blank keywords:  no keyword at all, just some text in the "value" area; bizarre

These are mainly following comment fields, whereas the normal usage is to just add more comment fields. I *think* this is how cfitsio normally does it, but not sure.

Also one of the column names is 'DE-' which is odd but might be valid.

Generally the header is not being fully parsed, but this may be a problem at the python level where I didn't even anticipate these no-name keywords.

**Comment by esheldon** [comment]
another clue.  This works

```python
f=fitsio.FITS('table1.fits')
print f[1]
f[1].read()
```
But if I leave off the print f[1] it seg faults

**Comment by esheldon** [comment]
(but then I do sometimes still get  a set fault, so that is probably just covering up a memory problem)

**Comment by esheldon** [comment]
Note pyfits reads this data incorrectly as well (not that this is a sign of a problem with the data, necessarily). yyfits gets most of the types wrong.

fitsio reports these types, which 
```python
  file: table1.fits
  extension: 1
  type: ASCII_TBL
  extname: table1.dat
  rows: 8
  column info:
    SN                  S9  
    RAh                 i4  
    RAm                 i4  
    RAs                 f8  
    DE-                 S1  
    DEd                 i4  
    DEm                 i4  
    DEs                 f8  
    z                   f8  
    r_SN               S39  
```

pyfits reads with these types
```python
  SN                 |S9  'SN 1999aa'
  RAh                |V1  '08'
  RAm                |S2  '27'
  RAs                |V1  '42.03'
  DE-                |S2  '+'
  DEd                |V1  '21'
  DEm                |S5  '29'
  DEs                |V1  '14.8'
  z                  |S1  '0.0142'
  r_SN               |S2  '1999IAUC.7180R...1C,1999I'...
```
pyfits seems to be getting confused by the formats, e.g.
```
TFORM2  = 'I2      '
```
So I can't use pyfits to test this either.  Writing the same data with cfitsio gives similar formats, just with some differences in the details of widths and things, and still gives a segfault

**Comment by kbarbary** [comment]
When fitsio didn't segfault (happened once or twice for me), it seemed to read the table correctly.

I gave up on using these FITS files. They are auto-generated from CDS-format text files (perhaps explains the wacky header), so I just switched to using the text files directly.

**Comment by esheldon** [comment]
it is probably still worth tracking this down, but it will probably require memory debugging which is difficult in python extensions; you can't run gdb

**Comment by esheldon** [comment]
I also saw a problem in a binary table with very large variable length strings. I'm not sure if it is related yet

**Comment by esheldon** [comment]
I'm going to close this, not because it is resolved, but because it is unlikely we will spend any more time on it as these files seem to be non-standard.
