### ISSUE TITLE
Add support for bz2-compressed files

### ISSUE THREAD

**Issue by parejkoj** [esheldon/fitsio#60]
cfitsio 3.37 added support for direct reading of bz2 compressed files (like the SDSS frame files: http://data.sdss3.org/sas/dr12/boss/photoObj/frames/301/6073/4/frame-u-006073-4-0063.fits.bz2 ). It would be useful to have this support in fitsio as well.

**Comment by esheldon** [comment]
fitsio uses 3.37 already.  Are you using an old fitsio?

**Comment by parejkoj** [comment]
Oh, good catch. I was on 0.9.3. Upgraded to 0.9.7, but now I get this:

```In [7]: fitsio.read('/Users/parejkoj/lsst/dev/obs_sdss/tests/data/dr12/frames/301/94/1/frame-g-000094-1-0131.fits.bz2')
ERROR - failed to write data to stream: <open file '<stdout>', mode 'w' at 0x10028e150>```

**Comment by esheldon** [comment]
Odd, I get a different error
```
IOError: FITSIO status = 252: 1st key not SIMPLE or XTENSION
Extension doesn't start with SIMPLE or XTENSION keyword. (ffrhdu)
BZh91AY&SY�j�֢������������������������������������ 
ffopen could not interpret primary array header of file: 
frame-u-006073-4-0063.fits.bz2
This does not look like a FITS file.
```

**Comment by esheldon** [comment]
So bzip is available for tile compression of images, but I don't think reading the bzipped fits file is supported.

We might be able to hack something where the bzip file is uncompressed to a temporary file which is opened by fitsio, but this would not work for writing

**Comment by esheldon** [comment]
Actually I think I'm wrong about that, sorry.  Probably your bzlib library wasn't found during cfitsio compilation

**Comment by parejkoj** [comment]
Hmm... I see this inside the build commands: `-DHAVE_BZLIB_H=1 -DHAVE_BZIP2=1` when building with `pip -v install fitsio --no-cache-dir`. Not sure what else I should see to confirm it found it.

**Comment by esheldon** [comment]
I also see that in the compilation, but the final .so does not show the library
```
[esheldon@rohan fitsio] ldd build/lib.linux-x86_64-2.7/fitsio/_fitsio_wrap.so 
        linux-vdso.so.1 =>  (0x00007fff5adf6000)
        libpython2.7.so.1.0 => /home/esheldon/anaconda/lib/libpython2.7.so.1.0 (0x00007fecc6231000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fecc6014000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fecc5c56000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007fecc5a52000)
        libutil.so.1 => /lib/x86_64-linux-gnu/libutil.so.1 (0x00007fecc584f000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fecc5553000)
        /lib64/ld-linux-x86-64.so.2 (0x00007fecc6a03000)
```

I also added --with-bzlib2 to the configure call and that didn't change anything.

**Comment by esheldon** [comment]
@dstndstn have you gotten bzipped files to work with fitsio?  I see you added bzip support to cfitsio

**Comment by dstndstn** [comment]
In my old pull request, #15 , two changes were to cfitsio files; those were pushed upstream and appeared in CFITSIO 3.370.  There were also two changes to fitsio files -- I added a test case, and it was also necessary to add bz2 to the list of linked libraries.

I just added a new pull request, #61, with those changes... but I just noticed that the test case does not run, so give me a second to figure out what's going on...

**Comment by dstndstn** [comment]
... it's going to take more than a second... appears that some of my bzip2 changes didn't actually make it into 3.370...

**Comment by dstndstn** [comment]
See #61

**Comment by esheldon** [comment]
@parejkoj is this all working for you?

**Comment by parejkoj** [comment]
I pulled fitsio master and tested it on the same file that started this whole thing, and it appears to work. Thank you!
