### ISSUE TITLE
Should BUNIT be cleaned from the header?

### ISSUE THREAD

**Issue by esheldon** [esheldon/fitsio#75]
Generally, are there keywords being cleaned that should be kept?

**Comment by esheldon** [comment]
The motivation of cleaning is to prevent special keywords from getting over-written, such as column defs or compression keywords

**Comment by esheldon** [comment]
I think the following keywords should not be cleaned for images
```
bunit, bscale, bzero
```
but they *should* be cleaned for tables, since fitsverify doesn't like them

http://heasarc.gsfc.nasa.gov/docs/software/ftools/fitsverify/

**Comment by esheldon** [comment]
Current master implements this, but I would like to hear from others

**Comment by jamiefarnes** [comment]
Hi,
I'm currently processing some images, and reading/writing using fitsio. The BUNIT is an important header attribute for this (giving units Jy/beam, which other software uses for scaling), but this is currently wiped when writing. Currently trying to find a workaround, to keep the header intact.
Cheers

**Comment by esheldon** [comment]
I thought these would only be cleaned from tables.  What version of fitsio are you using?

You can also turn off cleaning with clean=False

**Comment by jamiefarnes** [comment]
Hi Erin,
Thank you for the fast reply. Update to latest version and adding clean=False fixed everything.
Cheers

**Comment by esheldon** [comment]
Since this required clean=False, I take it you are working with tables since BUNIT is not cleaned from images.  Can you give some insight into how BUNIT is being used in a table?

**Comment by jamiefarnes** [comment]
I think the clean=False was not necessary here, as working with images. Likely the version update alone fixed everything.
