### ISSUE TITLE
Existing image data not overwritten if different shape

### ISSUE THREAD

**Issue by mindriot101** [esheldon/fitsio#76]
Hi, I've been trying to replace the data in an image HDU with new values.
In the documentation for `fitsio.fitslib.ImageHDU.write` it states that 

> If data already exist in this HDU, they will be overwritten

This works if the new image data is the same shape as the old image data, but
not if they are different. The code below shows an example where this is the
case. Perhaps a call to `fits_resize_img` could be done conditionally in
`PyFITSObject_write_image`? I'm happy to look into this if I get time.

Thanks,
Simon

```python
import fitsio
import numpy as np

initial_data = np.zeros((5, 5))
replacement_data = np.ones((6, 6))

# Sanity check
assert replacement_data.shape != initial_data.shape

# Write the initial data and let fitsio flush to disc
with fitsio.FITS('output.fits', 'rw', clobber=True) as outfile:
    outfile.write(initial_data)

# Update the image data, and flush to disc. As quoted in the source:
#  "If data already exist in this HDU, they will be overwritten"
# https://github.com/esheldon/fitsio/blob/20dc93976a75116d74b2c98896cbbc4ff3bfdefd/fitsio/fitslib.py#L2904
with fitsio.FITS('output.fits', 'rw') as outfile:
    outfile[0].write(replacement_data)

with fitsio.FITS('output.fits') as infile:
    image_shape = infile[0].get_info()['dims']

    # Passing this test means at least the first element was overwritten
    assert infile[0],read()[0][0] == replacement_data[0][0]

    # Check the image shape. A failed assertion means the new array shape is
    # different
    expected = list(map(long, replacement_data.shape))
    assert image_shape == expected, (
        'image shape: %s, expected: %s' % (image_shape, expected)
    )
```

**Comment by esheldon** [comment]
This shouldn't be too hard to support.  I'll look into it.

**Comment by esheldon** [comment]
This works for me now using master, please give it a try

**Comment by mindriot101** [comment]
Based on the existing documentation I thought that `ImageHDU.write` would overwrite the data in the HDU. Currently with your new changes (which work well btw) if the new image is bigger then the new data is overwritten, but if the new image is _smaller_ then it overwrites the data but does not resize the image.

My feeling is that calling `ImageHDU.write` with any data would replace the existing data, no matter what size it is. What do you think?

**Comment by esheldon** [comment]
The current behavior mirrors what happens with tables if you write in
place: the table is expanded but never contracted.  that is a feature
of cfitsio table writes.  So I did this to be consistent.

There is a new image hdu method called reshape() that you can use to
get any shape you like.



On 1/15/16, Simon Walker <notifications@github.com> wrote:
> Based on the existing documentation I thought that `ImageHDU.write` would
> overwrite the data in the HDU. Currently with your new changes (which work
> well btw) if the new image is bigger then the new data is overwritten, but
> if the new image is _smaller_ then it overwrites the data but does not
> resize the image.
>
> My feeling is that calling `ImageHDU.write` with any data would replace the
> existing data, no matter what size it is. What do you think?
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/esheldon/fitsio/issues/76#issuecomment-172095606


-- 
Erin Scott Sheldon
Brookhaven National Laboratory erin dot sheldon at gmail dot com

**Comment by mindriot101** [comment]
Yes that works well, and as you say the new behaviour is in line with the table
behaviour. Is there a corresponding table resize() method?
