### ISSUE TITLE
Failure in installing fitsio using either pip or the standard way

### ISSUE THREAD

**Issue by mehdirezaie** [esheldon/fitsio#78]
Dear All,

I have come across some complaints when I tried to install the fitsio module on my system (OS X). For your information, I need "fitsio" as a prerequisite of the Astrometry.net code.

I tried both ways of installing "fitsio", either pip or downloading the tar file (untaring, and running "python setup.py"). None of has been successful. I get error that says a code (fitsio_pywrap.c in firsio directory) is missing the fitsio.h file:

fitsio/fitsio_pywrap.c:25:10: fatal error: 'fitsio.h' file not found

I was hoping if someone has ever come across this problem during the "fitsio" installation. I would sincerely appreciate any comments and help.

Thank you,
- Mehdi

**Comment by esheldon** [comment]
The environment on macs tends to be very different from computer to computer, due to using different python installs, compilers, distributions (homebrew etc).  I think we need more details about your system before diagnosing.

Also, I don't currently have a mac for testing, so I will need some input from others to diagnose.

**Comment by mehdirezaie** [comment]
@esheldon
Thank you very much. Actually I needed "fitsio" to install "Astrometry.Net", and that to install "Tractor" on my Mac. After trying many ways, I could finally solve my issue. I downloaded the Astrometry.net source from "http://astrometry.net/use.html", and then I followed the instructions explained in "http://astrometry.net/doc/build.html#build" to set up the prerequisites (including cfitsio), namely I typed:

$ brew install --HEAD --use-gcc netpbm
$ brew install cfitsio --with-examples
$ brew install md5sha1sum

Then I moved into the astrometry installation directory, and ran following commands,

$ make install INSTALL_DIR=/usr/local/astrometry
$ export PYTHONPATH=${PYTHONPATH}:/usr/local/astrometry/lib/python


Speaking of details about my system, would you please tell me what you would like exactly to know.?

Thank you,
-M

**Comment by esheldon** [comment]
OK, it looks like it was a distribution problem.  Do you considered this solved?

**Comment by mehdirezaie** [comment]
For this case, I think it is solved. But for my future reference, do you have any recommendation or something? I would sincerely appreciate that.

**Comment by esheldon** [comment]
I'm sorry, I can't make any recommendations.  I don't have a mac, and I have not tried Tractor + fitsio

Maybe @dstndstn can comment as the author of Tractor and Mac user

**Comment by dstndstn** [comment]
well, the only explanation I have is that you installed cfitsio via homebrew, so I guess fitsio found the fitsio.h header from there.  But I thought fitsio shipped with its own version of the cfitsio library, so I'm not sure why that was necessary.

**Comment by beckermr** [comment]
There is an install option to have fitsio *look* for a locally installed version of cfitsio. This option has no official support, but might be useful in certain situations where the regular install get confused.

**Comment by mehdirezaie** [comment]
Thank you, all, for your help. :)
I am closing this issue.
