### ISSUE TITLE
run unit tests in travis

### ISSUE THREAD

**Issue by esheldon** [esheldon/fitsio#96]
Not sure how to do this and have the result propagate to show failure.

Also the bzip test often fails because many systems do not have bzip headers installed, or the library. We would need to make sure everything is installed so that test doesn't fail.

**Comment by dneise** [comment]
You could use pytest to execute your unittests, like I do it currently here in [the forked version](https://github.com/dneise/fitsio/blob/786e22c9669222cde42dee9ecc3ebdcfe22d1070/.travis.yml)

On my laptop I do not have the bzip headers installed and the test nicely fails. 
In addition the return code of the `py.test` is not zero

~~~
dneise@lair:~/fitsio_dneise_fork$ py.test
===================================== test session starts =====================================
platform linux -- Python 3.5.2, pytest-2.9.2, py-1.4.31, pluggy-0.3.1
rootdir: /home/dneise/fitsio_dneise_fork, inifile: 
collected 30 items 

fitsio/test_all.py ...F..........................

========================================== FAILURES ===========================================
__________________________________ TestReadWrite.testBz2Read __________________________________
[....lots of text....]
OSError
============================= 1 failed, 29 passed in 1.02 seconds =============================
~~~
and then
~~~
dneise@lair:~/fitsio_dneise_fork$ echo $?
1
~~~

This way `travis` can see that the tests failed, as far as I understood.... 

I am currently too stupid to find something about the `pytest` exit code in the docu ...

**Comment by esheldon** [comment]
working now with a series of commits ending with 0ae5ab1ec2149e4cdd053cd6e33cc37acc35f66d
