### ISSUE TITLE
HIERARCH keywords

### ISSUE THREAD

**Issue by thusser** [esheldon/fitsio#98]
Hi,

I'd like to use fitsio as a replacement for a dfits/fitsort call on thousands of FITS files, which is way faster than using pyfits. Unfortunately it seems that fitsio doesn't handle HIERARCH keywords correctly. This doesn't work:
```
hdr = fitsio.read_header(f)
print(hdr['HIERARCH SOME LONG KEYWORD'])
```
And hdr.keys() only gives a long list of COMMENT keywords... So how do I handle HIERARCH keywords correctly (if at all)?
Thanks.

Cheers,
Tim

**Comment by esheldon** [comment]
Thanks for the bug report.  Can you please post an example file?  Also, can you please give an example script that shows that demonstrates what the correct answer should be?

**Comment by thusser** [comment]
Sure, here is a a very simple FITS file and a Python script that reads a keyword from it. The script contains both the pyfits (as bundled in astropy) and the fitsio version. In both the header keyword is accessed in two different ways, once with the HIERARCH keyword and once without.
In pyfits this works, in fitsio it doesn't.

[test.zip](https://github.com/esheldon/fitsio/files/445078/test.zip)

**Comment by esheldon** [comment]
I have fixed this in the master branch. Please give it a try.

**Comment by thusser** [comment]
Works like a charm. Thanks a lot! :+1:

**Comment by esheldon** [comment]
ok to close?

**Comment by thusser** [comment]
Yes, thanks again.
